// ─── Hardcoded WC 2026 Predicted Starting Lineups ────────────────────────────
// Used as guaranteed fallback when TheSportsDB API and AI both fail to provide lineups.
// Sorted: GK → DEF → MID → FWD

export interface SquadPlayer {
  name: string;
  number: number;
  position: string;
}

const WC_SQUADS: Record<string, SquadPlayer[]> = {
  // ─── PORTUGAL ───────────────────────────────────────────────────────────────
  Portugal: [
    { name: 'Diogo Costa', number: 1, position: 'Goalkeeper' },
    { name: 'João Cancelo', number: 20, position: 'Defender' },
    { name: 'Rúben Dias', number: 6, position: 'Defender' },
    { name: 'António Silva', number: 4, position: 'Defender' },
    { name: 'Nuno Mendes', number: 19, position: 'Defender' },
    { name: 'João Palhinha', number: 26, position: 'Midfielder' },
    { name: 'Vitinha', number: 10, position: 'Midfielder' },
    { name: 'Bruno Fernandes', number: 8, position: 'Midfielder' },
    { name: 'Bernardo Silva', number: 10, position: 'Midfielder' },
    { name: 'Rafael Leão', number: 17, position: 'Forward' },
    { name: 'Cristiano Ronaldo', number: 7, position: 'Forward' },
  ],
  // ─── ESPAÑA ─────────────────────────────────────────────────────────────────
  España: [
    { name: 'Unai Simón', number: 23, position: 'Goalkeeper' },
    { name: 'Dani Carvajal', number: 2, position: 'Defender' },
    { name: 'Robin Le Normand', number: 14, position: 'Defender' },
    { name: 'Aymeric Laporte', number: 5, position: 'Defender' },
    { name: 'Marc Cucurella', number: 24, position: 'Defender' },
    { name: 'Rodri', number: 16, position: 'Midfielder' },
    { name: 'Pedri', number: 8, position: 'Midfielder' },
    { name: 'Fabián Ruiz', number: 18, position: 'Midfielder' },
    { name: 'Lamine Yamal', number: 19, position: 'Forward' },
    { name: 'Álvaro Morata', number: 9, position: 'Forward' },
    { name: 'Nico Williams', number: 17, position: 'Forward' },
  ],
  // ─── FRANCE ─────────────────────────────────────────────────────────────────
  Francia: [
    { name: 'Mike Maignan', number: 16, position: 'Goalkeeper' },
    { name: 'Jules Koundé', number: 5, position: 'Defender' },
    { name: 'William Saliba', number: 17, position: 'Defender' },
    { name: 'Dayot Upamecano', number: 4, position: 'Defender' },
    { name: 'Theo Hernandez', number: 22, position: 'Defender' },
    { name: 'Aurélien Tchouaméni', number: 8, position: 'Midfielder' },
    { name: 'Eduardo Camavinga', number: 14, position: 'Midfielder' },
    { name: 'Antoine Griezmann', number: 7, position: 'Midfielder' },
    { name: 'Ousmane Dembélé', number: 11, position: 'Forward' },
    { name: 'Kylian Mbappé', number: 10, position: 'Forward' },
    { name: 'Marcus Thuram', number: 9, position: 'Forward' },
  ],
  France: [
    { name: 'Mike Maignan', number: 16, position: 'Goalkeeper' },
    { name: 'Jules Koundé', number: 5, position: 'Defender' },
    { name: 'William Saliba', number: 17, position: 'Defender' },
    { name: 'Dayot Upamecano', number: 4, position: 'Defender' },
    { name: 'Theo Hernandez', number: 22, position: 'Defender' },
    { name: 'Aurélien Tchouaméni', number: 8, position: 'Midfielder' },
    { name: 'Eduardo Camavinga', number: 14, position: 'Midfielder' },
    { name: 'Antoine Griezmann', number: 7, position: 'Midfielder' },
    { name: 'Ousmane Dembélé', number: 11, position: 'Forward' },
    { name: 'Kylian Mbappé', number: 10, position: 'Forward' },
    { name: 'Marcus Thuram', number: 9, position: 'Forward' },
  ],
  // ─── GERMANY ────────────────────────────────────────────────────────────────
  Alemania: [
    { name: 'Manuel Neuer', number: 1, position: 'Goalkeeper' },
    { name: 'Joshua Kimmich', number: 6, position: 'Defender' },
    { name: 'Antonio Rüdiger', number: 2, position: 'Defender' },
    { name: 'Niklas Süle', number: 15, position: 'Defender' },
    { name: 'David Raum', number: 3, position: 'Defender' },
    { name: 'Ilkay Gündogan', number: 21, position: 'Midfielder' },
    { name: 'Florian Wirtz', number: 10, position: 'Midfielder' },
    { name: 'Jamal Musiala', number: 14, position: 'Midfielder' },
    { name: 'Leroy Sané', number: 19, position: 'Forward' },
    { name: 'Kai Havertz', number: 7, position: 'Forward' },
    { name: 'Thomas Müller', number: 13, position: 'Forward' },
  ],
  Germany: [
    { name: 'Manuel Neuer', number: 1, position: 'Goalkeeper' },
    { name: 'Joshua Kimmich', number: 6, position: 'Defender' },
    { name: 'Antonio Rüdiger', number: 2, position: 'Defender' },
    { name: 'Niklas Süle', number: 15, position: 'Defender' },
    { name: 'David Raum', number: 3, position: 'Defender' },
    { name: 'Ilkay Gündogan', number: 21, position: 'Midfielder' },
    { name: 'Florian Wirtz', number: 10, position: 'Midfielder' },
    { name: 'Jamal Musiala', number: 14, position: 'Midfielder' },
    { name: 'Leroy Sané', number: 19, position: 'Forward' },
    { name: 'Kai Havertz', number: 7, position: 'Forward' },
    { name: 'Thomas Müller', number: 13, position: 'Forward' },
  ],
  // ─── BRASIL ─────────────────────────────────────────────────────────────────
  Brasil: [
    { name: 'Alisson', number: 1, position: 'Goalkeeper' },
    { name: 'Danilo', number: 2, position: 'Defender' },
    { name: 'Éder Militão', number: 3, position: 'Defender' },
    { name: 'Marquinhos', number: 4, position: 'Defender' },
    { name: 'Guilherme Arana', number: 6, position: 'Defender' },
    { name: 'Casemiro', number: 5, position: 'Midfielder' },
    { name: 'Lucas Paquetá', number: 10, position: 'Midfielder' },
    { name: 'Bruno Guimarães', number: 18, position: 'Midfielder' },
    { name: 'Rodrygo', number: 11, position: 'Forward' },
    { name: 'Vinicius Jr', number: 7, position: 'Forward' },
    { name: 'Raphinha', number: 19, position: 'Forward' },
  ],
  Brazil: [
    { name: 'Alisson', number: 1, position: 'Goalkeeper' },
    { name: 'Danilo', number: 2, position: 'Defender' },
    { name: 'Éder Militão', number: 3, position: 'Defender' },
    { name: 'Marquinhos', number: 4, position: 'Defender' },
    { name: 'Guilherme Arana', number: 6, position: 'Defender' },
    { name: 'Casemiro', number: 5, position: 'Midfielder' },
    { name: 'Lucas Paquetá', number: 10, position: 'Midfielder' },
    { name: 'Bruno Guimarães', number: 18, position: 'Midfielder' },
    { name: 'Rodrygo', number: 11, position: 'Forward' },
    { name: 'Vinicius Jr', number: 7, position: 'Forward' },
    { name: 'Raphinha', number: 19, position: 'Forward' },
  ],
  // ─── ARGENTINA ──────────────────────────────────────────────────────────────
  Argentina: [
    { name: 'E. Martínez', number: 23, position: 'Goalkeeper' },
    { name: 'Nahuel Molina', number: 26, position: 'Defender' },
    { name: 'Cristian Romero', number: 13, position: 'Defender' },
    { name: 'Nicolás Otamendi', number: 19, position: 'Defender' },
    { name: 'Marcos Acuña', number: 8, position: 'Defender' },
    { name: 'Rodrigo De Paul', number: 7, position: 'Midfielder' },
    { name: 'Leandro Paredes', number: 5, position: 'Midfielder' },
    { name: 'Alexis Mac Allister', number: 20, position: 'Midfielder' },
    { name: 'Lionel Messi', number: 10, position: 'Forward' },
    { name: 'Lautaro Martínez', number: 22, position: 'Forward' },
    { name: 'Julián Álvarez', number: 9, position: 'Forward' },
  ],
  // ─── ENGLAND ────────────────────────────────────────────────────────────────
  Inglaterra: [
    { name: 'Jordan Pickford', number: 1, position: 'Goalkeeper' },
    { name: 'Trent Alexander-Arnold', number: 66, position: 'Defender' },
    { name: 'John Stones', number: 5, position: 'Defender' },
    { name: 'Harry Maguire', number: 6, position: 'Defender' },
    { name: 'Luke Shaw', number: 3, position: 'Defender' },
    { name: 'Declan Rice', number: 4, position: 'Midfielder' },
    { name: 'Jude Bellingham', number: 22, position: 'Midfielder' },
    { name: 'Phil Foden', number: 47, position: 'Midfielder' },
    { name: 'Bukayo Saka', number: 17, position: 'Forward' },
    { name: 'Harry Kane', number: 9, position: 'Forward' },
    { name: 'Marcus Rashford', number: 11, position: 'Forward' },
  ],
  England: [
    { name: 'Jordan Pickford', number: 1, position: 'Goalkeeper' },
    { name: 'Trent Alexander-Arnold', number: 66, position: 'Defender' },
    { name: 'John Stones', number: 5, position: 'Defender' },
    { name: 'Harry Maguire', number: 6, position: 'Defender' },
    { name: 'Luke Shaw', number: 3, position: 'Defender' },
    { name: 'Declan Rice', number: 4, position: 'Midfielder' },
    { name: 'Jude Bellingham', number: 22, position: 'Midfielder' },
    { name: 'Phil Foden', number: 47, position: 'Midfielder' },
    { name: 'Bukayo Saka', number: 17, position: 'Forward' },
    { name: 'Harry Kane', number: 9, position: 'Forward' },
    { name: 'Marcus Rashford', number: 11, position: 'Forward' },
  ],
  // ─── NETHERLANDS ────────────────────────────────────────────────────────────
  Holanda: [
    { name: 'Bart Verbruggen', number: 1, position: 'Goalkeeper' },
    { name: 'Denzel Dumfries', number: 22, position: 'Defender' },
    { name: 'Virgil van Dijk', number: 4, position: 'Defender' },
    { name: 'Matthijs de Ligt', number: 3, position: 'Defender' },
    { name: 'Nathan Aké', number: 5, position: 'Defender' },
    { name: 'Frenkie de Jong', number: 21, position: 'Midfielder' },
    { name: 'Tijjani Reijnders', number: 8, position: 'Midfielder' },
    { name: 'Xavi Simons', number: 10, position: 'Midfielder' },
    { name: 'Cody Gakpo', number: 11, position: 'Forward' },
    { name: 'Memphis Depay', number: 9, position: 'Forward' },
    { name: 'Donyell Malen', number: 7, position: 'Forward' },
  ],
  Netherlands: [
    { name: 'Bart Verbruggen', number: 1, position: 'Goalkeeper' },
    { name: 'Denzel Dumfries', number: 22, position: 'Defender' },
    { name: 'Virgil van Dijk', number: 4, position: 'Defender' },
    { name: 'Matthijs de Ligt', number: 3, position: 'Defender' },
    { name: 'Nathan Aké', number: 5, position: 'Defender' },
    { name: 'Frenkie de Jong', number: 21, position: 'Midfielder' },
    { name: 'Tijjani Reijnders', number: 8, position: 'Midfielder' },
    { name: 'Xavi Simons', number: 10, position: 'Midfielder' },
    { name: 'Cody Gakpo', number: 11, position: 'Forward' },
    { name: 'Memphis Depay', number: 9, position: 'Forward' },
    { name: 'Donyell Malen', number: 7, position: 'Forward' },
  ],
  // ─── MOROCCO ────────────────────────────────────────────────────────────────
  Marruecos: [
    { name: 'Bono', number: 1, position: 'Goalkeeper' },
    { name: 'Achraf Hakimi', number: 2, position: 'Defender' },
    { name: 'Nayef Aguerd', number: 5, position: 'Defender' },
    { name: 'Romain Saïss', number: 21, position: 'Defender' },
    { name: 'Noussair Mazraoui', number: 3, position: 'Defender' },
    { name: 'Sofyan Amrabat', number: 4, position: 'Midfielder' },
    { name: 'Azzedine Ounahi', number: 8, position: 'Midfielder' },
    { name: 'Hakim Ziyech', number: 7, position: 'Midfielder' },
    { name: 'Sofiane Boufal', number: 11, position: 'Forward' },
    { name: 'Youssef En-Nesyri', number: 19, position: 'Forward' },
    { name: 'Walid Cheddira', number: 9, position: 'Forward' },
  ],
  Morocco: [
    { name: 'Bono', number: 1, position: 'Goalkeeper' },
    { name: 'Achraf Hakimi', number: 2, position: 'Defender' },
    { name: 'Nayef Aguerd', number: 5, position: 'Defender' },
    { name: 'Romain Saïss', number: 21, position: 'Defender' },
    { name: 'Noussair Mazraoui', number: 3, position: 'Defender' },
    { name: 'Sofyan Amrabat', number: 4, position: 'Midfielder' },
    { name: 'Azzedine Ounahi', number: 8, position: 'Midfielder' },
    { name: 'Hakim Ziyech', number: 7, position: 'Midfielder' },
    { name: 'Sofiane Boufal', number: 11, position: 'Forward' },
    { name: 'Youssef En-Nesyri', number: 19, position: 'Forward' },
    { name: 'Walid Cheddira', number: 9, position: 'Forward' },
  ],
  // ─── USA ────────────────────────────────────────────────────────────────────
  USA: [
    { name: 'Matt Turner', number: 1, position: 'Goalkeeper' },
    { name: 'Sergino Dest', number: 2, position: 'Defender' },
    { name: 'Miles Robinson', number: 12, position: 'Defender' },
    { name: 'Walker Zimmerman', number: 3, position: 'Defender' },
    { name: 'Antonee Robinson', number: 5, position: 'Defender' },
    { name: 'Tyler Adams', number: 4, position: 'Midfielder' },
    { name: 'Weston McKennie', number: 8, position: 'Midfielder' },
    { name: 'Christian Pulisic', number: 10, position: 'Midfielder' },
    { name: 'Giovanni Reyna', number: 7, position: 'Forward' },
    { name: 'Josh Sargent', number: 9, position: 'Forward' },
    { name: 'Tim Weah', number: 21, position: 'Forward' },
  ],
  'Estados Unidos': [
    { name: 'Matt Turner', number: 1, position: 'Goalkeeper' },
    { name: 'Sergino Dest', number: 2, position: 'Defender' },
    { name: 'Miles Robinson', number: 12, position: 'Defender' },
    { name: 'Walker Zimmerman', number: 3, position: 'Defender' },
    { name: 'Antonee Robinson', number: 5, position: 'Defender' },
    { name: 'Tyler Adams', number: 4, position: 'Midfielder' },
    { name: 'Weston McKennie', number: 8, position: 'Midfielder' },
    { name: 'Christian Pulisic', number: 10, position: 'Midfielder' },
    { name: 'Giovanni Reyna', number: 7, position: 'Forward' },
    { name: 'Josh Sargent', number: 9, position: 'Forward' },
    { name: 'Tim Weah', number: 21, position: 'Forward' },
  ],
  // ─── MEXICO ─────────────────────────────────────────────────────────────────
  México: [
    { name: 'Guillermo Ochoa', number: 13, position: 'Goalkeeper' },
    { name: 'Jorge Sánchez', number: 2, position: 'Defender' },
    { name: 'Nestor Araujo', number: 4, position: 'Defender' },
    { name: 'Johan Vásquez', number: 15, position: 'Defender' },
    { name: 'Jesús Gallardo', number: 3, position: 'Defender' },
    { name: 'Edson Álvarez', number: 18, position: 'Midfielder' },
    { name: 'Carlos Rodríguez', number: 7, position: 'Midfielder' },
    { name: 'Héctor Herrera', number: 16, position: 'Midfielder' },
    { name: 'Hirving Lozano', number: 22, position: 'Forward' },
    { name: 'Santiago Giménez', number: 9, position: 'Forward' },
    { name: 'Henry Martín', number: 14, position: 'Forward' },
  ],
  Mexico: [
    { name: 'Guillermo Ochoa', number: 13, position: 'Goalkeeper' },
    { name: 'Jorge Sánchez', number: 2, position: 'Defender' },
    { name: 'Nestor Araujo', number: 4, position: 'Defender' },
    { name: 'Johan Vásquez', number: 15, position: 'Defender' },
    { name: 'Jesús Gallardo', number: 3, position: 'Defender' },
    { name: 'Edson Álvarez', number: 18, position: 'Midfielder' },
    { name: 'Carlos Rodríguez', number: 7, position: 'Midfielder' },
    { name: 'Héctor Herrera', number: 16, position: 'Midfielder' },
    { name: 'Hirving Lozano', number: 22, position: 'Forward' },
    { name: 'Santiago Giménez', number: 9, position: 'Forward' },
    { name: 'Henry Martín', number: 14, position: 'Forward' },
  ],
  // ─── CANADA ─────────────────────────────────────────────────────────────────
  Canadá: [
    { name: 'Milan Borjan', number: 18, position: 'Goalkeeper' },
    { name: 'Alistair Johnston', number: 2, position: 'Defender' },
    { name: 'Kamal Miller', number: 3, position: 'Defender' },
    { name: 'Derek Cornelius', number: 4, position: 'Defender' },
    { name: 'Richie Laryea', number: 22, position: 'Defender' },
    { name: 'Atiba Hutchinson', number: 13, position: 'Midfielder' },
    { name: 'Stephen Eustáquio', number: 7, position: 'Midfielder' },
    { name: 'Jonathan Osorio', number: 21, position: 'Midfielder' },
    { name: 'Alphonso Davies', number: 19, position: 'Forward' },
    { name: 'Jonathan David', number: 20, position: 'Forward' },
    { name: 'Tajon Buchanan', number: 11, position: 'Forward' },
  ],
  Canada: [
    { name: 'Milan Borjan', number: 18, position: 'Goalkeeper' },
    { name: 'Alistair Johnston', number: 2, position: 'Defender' },
    { name: 'Kamal Miller', number: 3, position: 'Defender' },
    { name: 'Derek Cornelius', number: 4, position: 'Defender' },
    { name: 'Richie Laryea', number: 22, position: 'Defender' },
    { name: 'Atiba Hutchinson', number: 13, position: 'Midfielder' },
    { name: 'Stephen Eustáquio', number: 7, position: 'Midfielder' },
    { name: 'Jonathan Osorio', number: 21, position: 'Midfielder' },
    { name: 'Alphonso Davies', number: 19, position: 'Forward' },
    { name: 'Jonathan David', number: 20, position: 'Forward' },
    { name: 'Tajon Buchanan', number: 11, position: 'Forward' },
  ],
  // ─── JAPAN ──────────────────────────────────────────────────────────────────
  Japón: [
    { name: 'Shuichi Gonda', number: 12, position: 'Goalkeeper' },
    { name: 'Hiroki Sakai', number: 5, position: 'Defender' },
    { name: 'Ko Itakura', number: 16, position: 'Defender' },
    { name: 'Maya Yoshida', number: 22, position: 'Defender' },
    { name: 'Yuto Nagatomo', number: 6, position: 'Defender' },
    { name: 'Wataru Endo', number: 17, position: 'Midfielder' },
    { name: 'Hidemasa Morita', number: 10, position: 'Midfielder' },
    { name: 'Daichi Kamada', number: 14, position: 'Midfielder' },
    { name: 'Junya Ito', number: 19, position: 'Forward' },
    { name: 'Kaoru Mitoma', number: 11, position: 'Forward' },
    { name: 'Takumi Minamino', number: 9, position: 'Forward' },
  ],
  Japan: [
    { name: 'Shuichi Gonda', number: 12, position: 'Goalkeeper' },
    { name: 'Hiroki Sakai', number: 5, position: 'Defender' },
    { name: 'Ko Itakura', number: 16, position: 'Defender' },
    { name: 'Maya Yoshida', number: 22, position: 'Defender' },
    { name: 'Yuto Nagatomo', number: 6, position: 'Defender' },
    { name: 'Wataru Endo', number: 17, position: 'Midfielder' },
    { name: 'Hidemasa Morita', number: 10, position: 'Midfielder' },
    { name: 'Daichi Kamada', number: 14, position: 'Midfielder' },
    { name: 'Junya Ito', number: 19, position: 'Forward' },
    { name: 'Kaoru Mitoma', number: 11, position: 'Forward' },
    { name: 'Takumi Minamino', number: 9, position: 'Forward' },
  ],
  // ─── CROATIA ────────────────────────────────────────────────────────────────
  Croacia: [
    { name: 'Dominik Livaković', number: 1, position: 'Goalkeeper' },
    { name: 'Josip Stanišić', number: 17, position: 'Defender' },
    { name: 'Joško Gvardiol', number: 3, position: 'Defender' },
    { name: 'Dejan Lovren', number: 6, position: 'Defender' },
    { name: 'Borna Sosa', number: 15, position: 'Defender' },
    { name: 'Luka Modrić', number: 10, position: 'Midfielder' },
    { name: 'Marcelo Brozović', number: 11, position: 'Midfielder' },
    { name: 'Mateo Kovačić', number: 8, position: 'Midfielder' },
    { name: 'Ivan Perišić', number: 4, position: 'Forward' },
    { name: 'Andrej Kramarić', number: 9, position: 'Forward' },
    { name: 'Bruno Petković', number: 16, position: 'Forward' },
  ],
  Croatia: [
    { name: 'Dominik Livaković', number: 1, position: 'Goalkeeper' },
    { name: 'Josip Stanišić', number: 17, position: 'Defender' },
    { name: 'Joško Gvardiol', number: 3, position: 'Defender' },
    { name: 'Dejan Lovren', number: 6, position: 'Defender' },
    { name: 'Borna Sosa', number: 15, position: 'Defender' },
    { name: 'Luka Modrić', number: 10, position: 'Midfielder' },
    { name: 'Marcelo Brozović', number: 11, position: 'Midfielder' },
    { name: 'Mateo Kovačić', number: 8, position: 'Midfielder' },
    { name: 'Ivan Perišić', number: 4, position: 'Forward' },
    { name: 'Andrej Kramarić', number: 9, position: 'Forward' },
    { name: 'Bruno Petković', number: 16, position: 'Forward' },
  ],
  // ─── SENEGAL ────────────────────────────────────────────────────────────────
  Senegal: [
    { name: 'Édouard Mendy', number: 16, position: 'Goalkeeper' },
    { name: 'Youssouf Sabaly', number: 2, position: 'Defender' },
    { name: 'Kalidou Koulibaly', number: 3, position: 'Defender' },
    { name: 'Abdou Diallo', number: 5, position: 'Defender' },
    { name: 'Formose Mendy', number: 23, position: 'Defender' },
    { name: 'Idrissa Gueye', number: 17, position: 'Midfielder' },
    { name: 'Pape Gueye', number: 8, position: 'Midfielder' },
    { name: 'Nampalys Mendy', number: 6, position: 'Midfielder' },
    { name: 'Sadio Mané', number: 10, position: 'Forward' },
    { name: 'Ismaila Sarr', number: 19, position: 'Forward' },
    { name: 'Boulaye Dia', number: 9, position: 'Forward' },
  ],
  // ─── SWITZERLAND ────────────────────────────────────────────────────────────
  Suiza: [
    { name: 'Yann Sommer', number: 1, position: 'Goalkeeper' },
    { name: 'Silvan Widmer', number: 3, position: 'Defender' },
    { name: 'Manuel Akanji', number: 5, position: 'Defender' },
    { name: 'Fabian Schär', number: 4, position: 'Defender' },
    { name: 'Ricardo Rodríguez', number: 13, position: 'Defender' },
    { name: 'Granit Xhaka', number: 10, position: 'Midfielder' },
    { name: 'Remo Freuler', number: 23, position: 'Midfielder' },
    { name: 'Denis Zakaria', number: 8, position: 'Midfielder' },
    { name: 'Xherdan Shaqiri', number: 23, position: 'Forward' },
    { name: 'Breel Embolo', number: 7, position: 'Forward' },
    { name: 'Ruben Vargas', number: 16, position: 'Forward' },
  ],
  Switzerland: [
    { name: 'Yann Sommer', number: 1, position: 'Goalkeeper' },
    { name: 'Silvan Widmer', number: 3, position: 'Defender' },
    { name: 'Manuel Akanji', number: 5, position: 'Defender' },
    { name: 'Fabian Schär', number: 4, position: 'Defender' },
    { name: 'Ricardo Rodríguez', number: 13, position: 'Defender' },
    { name: 'Granit Xhaka', number: 10, position: 'Midfielder' },
    { name: 'Remo Freuler', number: 23, position: 'Midfielder' },
    { name: 'Denis Zakaria', number: 8, position: 'Midfielder' },
    { name: 'Xherdan Shaqiri', number: 23, position: 'Forward' },
    { name: 'Breel Embolo', number: 7, position: 'Forward' },
    { name: 'Ruben Vargas', number: 16, position: 'Forward' },
  ],
  // ─── BELGIUM ────────────────────────────────────────────────────────────────
  Bélgica: [
    { name: 'Thibaut Courtois', number: 1, position: 'Goalkeeper' },
    { name: 'Timothy Castagne', number: 2, position: 'Defender' },
    { name: 'Jan Vertonghen', number: 5, position: 'Defender' },
    { name: 'Toby Alderweireld', number: 4, position: 'Defender' },
    { name: 'Yannick Carrasco', number: 11, position: 'Defender' },
    { name: 'Kevin De Bruyne', number: 7, position: 'Midfielder' },
    { name: 'Axel Witsel', number: 6, position: 'Midfielder' },
    { name: 'Youri Tielemans', number: 8, position: 'Midfielder' },
    { name: 'Eden Hazard', number: 10, position: 'Forward' },
    { name: 'Romelu Lukaku', number: 9, position: 'Forward' },
    { name: 'Leandro Trossard', number: 19, position: 'Forward' },
  ],
  Belgium: [
    { name: 'Thibaut Courtois', number: 1, position: 'Goalkeeper' },
    { name: 'Timothy Castagne', number: 2, position: 'Defender' },
    { name: 'Jan Vertonghen', number: 5, position: 'Defender' },
    { name: 'Toby Alderweireld', number: 4, position: 'Defender' },
    { name: 'Yannick Carrasco', number: 11, position: 'Defender' },
    { name: 'Kevin De Bruyne', number: 7, position: 'Midfielder' },
    { name: 'Axel Witsel', number: 6, position: 'Midfielder' },
    { name: 'Youri Tielemans', number: 8, position: 'Midfielder' },
    { name: 'Eden Hazard', number: 10, position: 'Forward' },
    { name: 'Romelu Lukaku', number: 9, position: 'Forward' },
    { name: 'Leandro Trossard', number: 19, position: 'Forward' },
  ],
  // ─── URUGUAY ────────────────────────────────────────────────────────────────
  Uruguay: [
    { name: 'Fernando Muslera', number: 1, position: 'Goalkeeper' },
    { name: 'Nahitan Nández', number: 4, position: 'Defender' },
    { name: 'Diego Godín', number: 3, position: 'Defender' },
    { name: 'José María Giménez', number: 2, position: 'Defender' },
    { name: 'Mathías Olivera', number: 22, position: 'Defender' },
    { name: 'Rodrigo Bentancur', number: 6, position: 'Midfielder' },
    { name: 'Lucas Torreira', number: 8, position: 'Midfielder' },
    { name: 'Federico Valverde', number: 14, position: 'Midfielder' },
    { name: 'Darwin Núñez', number: 11, position: 'Forward' },
    { name: 'Luis Suárez', number: 9, position: 'Forward' },
    { name: 'Facundo Torres', number: 21, position: 'Forward' },
  ],
  // ─── COLOMBIA ───────────────────────────────────────────────────────────────
  Colombia: [
    { name: 'Camilo Vargas', number: 1, position: 'Goalkeeper' },
    { name: 'Daniel Muñoz', number: 2, position: 'Defender' },
    { name: 'Dávinson Sánchez', number: 6, position: 'Defender' },
    { name: 'Yerry Mina', number: 13, position: 'Defender' },
    { name: 'Johan Mojica', number: 16, position: 'Defender' },
    { name: 'Wilmar Barrios', number: 5, position: 'Midfielder' },
    { name: 'Mateus Uribe', number: 8, position: 'Midfielder' },
    { name: 'James Rodríguez', number: 10, position: 'Midfielder' },
    { name: 'Luis Díaz', number: 23, position: 'Forward' },
    { name: 'Falcao', number: 9, position: 'Forward' },
    { name: 'Rafael Santos Borré', number: 19, position: 'Forward' },
  ],
  // ─── DR CONGO ───────────────────────────────────────────────────────────────
  'R.D. Congo': [
    { name: 'Joël Kiassumbua', number: 1, position: 'Goalkeeper' },
    { name: 'Chancel Mbemba', number: 5, position: 'Defender' },
    { name: 'Marcel Tisserand', number: 4, position: 'Defender' },
    { name: 'Arthur Masuaku', number: 3, position: 'Defender' },
    { name: 'Dylan Batubinsika', number: 23, position: 'Defender' },
    { name: 'Paul-José Mpoku', number: 10, position: 'Midfielder' },
    { name: 'Yannick Bolasie', number: 7, position: 'Midfielder' },
    { name: 'Théo Bongonda', number: 11, position: 'Midfielder' },
    { name: 'Cédric Bakambu', number: 9, position: 'Forward' },
    { name: 'Silas Mvumpa', number: 17, position: 'Forward' },
    { name: 'Dieumerci Mbokani', number: 21, position: 'Forward' },
  ],
  'RD Congo': [
    { name: 'Joël Kiassumbua', number: 1, position: 'Goalkeeper' },
    { name: 'Chancel Mbemba', number: 5, position: 'Defender' },
    { name: 'Marcel Tisserand', number: 4, position: 'Defender' },
    { name: 'Arthur Masuaku', number: 3, position: 'Defender' },
    { name: 'Dylan Batubinsika', number: 23, position: 'Defender' },
    { name: 'Paul-José Mpoku', number: 10, position: 'Midfielder' },
    { name: 'Yannick Bolasie', number: 7, position: 'Midfielder' },
    { name: 'Théo Bongonda', number: 11, position: 'Midfielder' },
    { name: 'Cédric Bakambu', number: 9, position: 'Forward' },
    { name: 'Silas Mvumpa', number: 17, position: 'Forward' },
    { name: 'Dieumerci Mbokani', number: 21, position: 'Forward' },
  ],
  'DR Congo': [
    { name: 'Joël Kiassumbua', number: 1, position: 'Goalkeeper' },
    { name: 'Chancel Mbemba', number: 5, position: 'Defender' },
    { name: 'Marcel Tisserand', number: 4, position: 'Defender' },
    { name: 'Arthur Masuaku', number: 3, position: 'Defender' },
    { name: 'Dylan Batubinsika', number: 23, position: 'Defender' },
    { name: 'Paul-José Mpoku', number: 10, position: 'Midfielder' },
    { name: 'Yannick Bolasie', number: 7, position: 'Midfielder' },
    { name: 'Théo Bongonda', number: 11, position: 'Midfielder' },
    { name: 'Cédric Bakambu', number: 9, position: 'Forward' },
    { name: 'Silas Mvumpa', number: 17, position: 'Forward' },
    { name: 'Dieumerci Mbokani', number: 21, position: 'Forward' },
  ],
  'Rep. Dem. Congo': [
    { name: 'Joël Kiassumbua', number: 1, position: 'Goalkeeper' },
    { name: 'Chancel Mbemba', number: 5, position: 'Defender' },
    { name: 'Marcel Tisserand', number: 4, position: 'Defender' },
    { name: 'Arthur Masuaku', number: 3, position: 'Defender' },
    { name: 'Dylan Batubinsika', number: 23, position: 'Defender' },
    { name: 'Paul-José Mpoku', number: 10, position: 'Midfielder' },
    { name: 'Yannick Bolasie', number: 7, position: 'Midfielder' },
    { name: 'Théo Bongonda', number: 11, position: 'Midfielder' },
    { name: 'Cédric Bakambu', number: 9, position: 'Forward' },
    { name: 'Silas Mvumpa', number: 17, position: 'Forward' },
    { name: 'Dieumerci Mbokani', number: 21, position: 'Forward' },
  ],
  'Congo, DR': [
    { name: 'Joël Kiassumbua', number: 1, position: 'Goalkeeper' },
    { name: 'Chancel Mbemba', number: 5, position: 'Defender' },
    { name: 'Marcel Tisserand', number: 4, position: 'Defender' },
    { name: 'Arthur Masuaku', number: 3, position: 'Defender' },
    { name: 'Dylan Batubinsika', number: 23, position: 'Defender' },
    { name: 'Paul-José Mpoku', number: 10, position: 'Midfielder' },
    { name: 'Yannick Bolasie', number: 7, position: 'Midfielder' },
    { name: 'Théo Bongonda', number: 11, position: 'Midfielder' },
    { name: 'Cédric Bakambu', number: 9, position: 'Forward' },
    { name: 'Silas Mvumpa', number: 17, position: 'Forward' },
    { name: 'Dieumerci Mbokani', number: 21, position: 'Forward' },
  ],
  // ─── CAPE VERDE ─────────────────────────────────────────────────────────────
  'Cabo Verde': [
    { name: 'Vozinha', number: 1, position: 'Goalkeeper' },
    { name: 'Stopira', number: 4, position: 'Defender' },
    { name: 'Filho', number: 5, position: 'Defender' },
    { name: 'Bryan Teixeira', number: 3, position: 'Defender' },
    { name: 'Steven Fortes', number: 2, position: 'Defender' },
    { name: 'Garry Rodrigues', number: 7, position: 'Midfielder' },
    { name: 'Ryan Mendes', number: 10, position: 'Midfielder' },
    { name: 'Kenny Rocha', number: 6, position: 'Midfielder' },
    { name: 'Fali', number: 8, position: 'Midfielder' },
    { name: 'Djaniny', number: 9, position: 'Forward' },
    { name: 'Jovane Cabral', number: 11, position: 'Forward' },
  ],
  'Cape Verde': [
    { name: 'Vozinha', number: 1, position: 'Goalkeeper' },
    { name: 'Stopira', number: 4, position: 'Defender' },
    { name: 'Filho', number: 5, position: 'Defender' },
    { name: 'Bryan Teixeira', number: 3, position: 'Defender' },
    { name: 'Steven Fortes', number: 2, position: 'Defender' },
    { name: 'Garry Rodrigues', number: 7, position: 'Midfielder' },
    { name: 'Ryan Mendes', number: 10, position: 'Midfielder' },
    { name: 'Kenny Rocha', number: 6, position: 'Midfielder' },
    { name: 'Fali', number: 8, position: 'Midfielder' },
    { name: 'Djaniny', number: 9, position: 'Forward' },
    { name: 'Jovane Cabral', number: 11, position: 'Forward' },
  ],
  // ─── SOUTH AFRICA ───────────────────────────────────────────────────────────
  Sudáfrica: [
    { name: 'Ronwen Williams', number: 1, position: 'Goalkeeper' },
    { name: 'Reeve Frosler', number: 2, position: 'Defender' },
    { name: 'Rushine De Reuck', number: 4, position: 'Defender' },
    { name: 'Mothobi Mvala', number: 5, position: 'Defender' },
    { name: 'Sifiso Hlanti', number: 3, position: 'Defender' },
    { name: 'Ethan Ntshumayelo', number: 6, position: 'Midfielder' },
    { name: 'Themba Zwane', number: 10, position: 'Midfielder' },
    { name: 'Bongani Zungu', number: 8, position: 'Midfielder' },
    { name: 'Percy Tau', number: 7, position: 'Forward' },
    { name: 'Lyle Foster', number: 9, position: 'Forward' },
    { name: 'Lebo Mothiba', number: 11, position: 'Forward' },
  ],
  'South Africa': [
    { name: 'Ronwen Williams', number: 1, position: 'Goalkeeper' },
    { name: 'Reeve Frosler', number: 2, position: 'Defender' },
    { name: 'Rushine De Reuck', number: 4, position: 'Defender' },
    { name: 'Mothobi Mvala', number: 5, position: 'Defender' },
    { name: 'Sifiso Hlanti', number: 3, position: 'Defender' },
    { name: 'Ethan Ntshumayelo', number: 6, position: 'Midfielder' },
    { name: 'Themba Zwane', number: 10, position: 'Midfielder' },
    { name: 'Bongani Zungu', number: 8, position: 'Midfielder' },
    { name: 'Percy Tau', number: 7, position: 'Forward' },
    { name: 'Lyle Foster', number: 9, position: 'Forward' },
    { name: 'Lebo Mothiba', number: 11, position: 'Forward' },
  ],
  // ─── UZBEKISTAN ─────────────────────────────────────────────────────────────
  Uzbekistán: [
    { name: 'Utkir Yusupov', number: 1, position: 'Goalkeeper' },
    { name: 'Sanjar Tursunov', number: 2, position: 'Defender' },
    { name: 'Khojiakbar Alijonov', number: 4, position: 'Defender' },
    { name: 'Jasurbek Yakhshiboev', number: 5, position: 'Defender' },
    { name: 'Sherzod Nishonov', number: 3, position: 'Defender' },
    { name: 'Jaloliddin Masharipov', number: 10, position: 'Midfielder' },
    { name: 'Odiljon Hamrobekov', number: 8, position: 'Midfielder' },
    { name: 'Otabek Shukurov', number: 6, position: 'Midfielder' },
    { name: 'Eldor Shomurodov', number: 9, position: 'Forward' },
    { name: 'Islom Tukhtahujaev', number: 11, position: 'Forward' },
    { name: 'Dostonbek Khamdamov', number: 7, position: 'Forward' },
  ],
  Uzbekistan: [
    { name: 'Utkir Yusupov', number: 1, position: 'Goalkeeper' },
    { name: 'Sanjar Tursunov', number: 2, position: 'Defender' },
    { name: 'Khojiakbar Alijonov', number: 4, position: 'Defender' },
    { name: 'Jasurbek Yakhshiboev', number: 5, position: 'Defender' },
    { name: 'Sherzod Nishonov', number: 3, position: 'Defender' },
    { name: 'Jaloliddin Masharipov', number: 10, position: 'Midfielder' },
    { name: 'Odiljon Hamrobekov', number: 8, position: 'Midfielder' },
    { name: 'Otabek Shukurov', number: 6, position: 'Midfielder' },
    { name: 'Eldor Shomurodov', number: 9, position: 'Forward' },
    { name: 'Islom Tukhtahujaev', number: 11, position: 'Forward' },
    { name: 'Dostonbek Khamdamov', number: 7, position: 'Forward' },
  ],
  // ─── ALGERIA ────────────────────────────────────────────────────────────────
  Argelia: [
    { name: 'Raïs M\'Bolhi', number: 1, position: 'Goalkeeper' },
    { name: 'Youcef Atal', number: 2, position: 'Defender' },
    { name: 'Djamel Benlamri', number: 4, position: 'Defender' },
    { name: 'Ramy Bensebaïni', number: 3, position: 'Defender' },
    { name: 'Aïssa Mandi', number: 5, position: 'Defender' },
    { name: 'Nabil Bentaleb', number: 8, position: 'Midfielder' },
    { name: 'Sofiane Feghouli', number: 18, position: 'Midfielder' },
    { name: 'Nacer Chabli', number: 6, position: 'Midfielder' },
    { name: 'Riyad Mahrez', number: 7, position: 'Forward' },
    { name: 'Islam Slimani', number: 9, position: 'Forward' },
    { name: 'Yacine Brahimi', number: 10, position: 'Forward' },
  ],
  Algeria: [
    { name: 'Raïs M\'Bolhi', number: 1, position: 'Goalkeeper' },
    { name: 'Youcef Atal', number: 2, position: 'Defender' },
    { name: 'Djamel Benlamri', number: 4, position: 'Defender' },
    { name: 'Ramy Bensebaïni', number: 3, position: 'Defender' },
    { name: 'Aïssa Mandi', number: 5, position: 'Defender' },
    { name: 'Nabil Bentaleb', number: 8, position: 'Midfielder' },
    { name: 'Sofiane Feghouli', number: 18, position: 'Midfielder' },
    { name: 'Nacer Chabli', number: 6, position: 'Midfielder' },
    { name: 'Riyad Mahrez', number: 7, position: 'Forward' },
    { name: 'Islam Slimani', number: 9, position: 'Forward' },
    { name: 'Yacine Brahimi', number: 10, position: 'Forward' },
  ],
  // ─── POLAND ─────────────────────────────────────────────────────────────────
  Polonia: [
    { name: 'Wojciech Szczęsny', number: 1, position: 'Goalkeeper' },
    { name: 'Matty Cash', number: 2, position: 'Defender' },
    { name: 'Jan Bednarek', number: 5, position: 'Defender' },
    { name: 'Kamil Glik', number: 15, position: 'Defender' },
    { name: 'Nicola Zalewski', number: 17, position: 'Defender' },
    { name: 'Krzysztof Piątek', number: 7, position: 'Midfielder' },
    { name: 'Grzegorz Krychowiak', number: 10, position: 'Midfielder' },
    { name: 'Piotr Zieliński', number: 20, position: 'Midfielder' },
    { name: 'Kamil Grosicki', number: 11, position: 'Forward' },
    { name: 'Robert Lewandowski', number: 9, position: 'Forward' },
    { name: 'Arkadiusz Milik', number: 23, position: 'Forward' },
  ],
  Poland: [
    { name: 'Wojciech Szczęsny', number: 1, position: 'Goalkeeper' },
    { name: 'Matty Cash', number: 2, position: 'Defender' },
    { name: 'Jan Bednarek', number: 5, position: 'Defender' },
    { name: 'Kamil Glik', number: 15, position: 'Defender' },
    { name: 'Nicola Zalewski', number: 17, position: 'Defender' },
    { name: 'Krzysztof Piątek', number: 7, position: 'Midfielder' },
    { name: 'Grzegorz Krychowiak', number: 10, position: 'Midfielder' },
    { name: 'Piotr Zieliński', number: 20, position: 'Midfielder' },
    { name: 'Kamil Grosicki', number: 11, position: 'Forward' },
    { name: 'Robert Lewandowski', number: 9, position: 'Forward' },
    { name: 'Arkadiusz Milik', number: 23, position: 'Forward' },
  ],
  // ─── DENMARK ────────────────────────────────────────────────────────────────
  Dinamarca: [
    { name: 'Kasper Schmeichel', number: 1, position: 'Goalkeeper' },
    { name: 'Daniel Wass', number: 5, position: 'Defender' },
    { name: 'Simon Kjær', number: 4, position: 'Defender' },
    { name: 'Andreas Christensen', number: 6, position: 'Defender' },
    { name: 'Joakim Mæhle', number: 2, position: 'Defender' },
    { name: 'Thomas Delaney', number: 8, position: 'Midfielder' },
    { name: 'Pierre-Emile Højbjerg', number: 23, position: 'Midfielder' },
    { name: 'Christian Eriksen', number: 10, position: 'Midfielder' },
    { name: 'Mikkel Damsgaard', number: 16, position: 'Forward' },
    { name: 'Kasper Dolberg', number: 20, position: 'Forward' },
    { name: 'Yussuf Poulsen', number: 20, position: 'Forward' },
  ],
  Denmark: [
    { name: 'Kasper Schmeichel', number: 1, position: 'Goalkeeper' },
    { name: 'Daniel Wass', number: 5, position: 'Defender' },
    { name: 'Simon Kjær', number: 4, position: 'Defender' },
    { name: 'Andreas Christensen', number: 6, position: 'Defender' },
    { name: 'Joakim Mæhle', number: 2, position: 'Defender' },
    { name: 'Thomas Delaney', number: 8, position: 'Midfielder' },
    { name: 'Pierre-Emile Højbjerg', number: 23, position: 'Midfielder' },
    { name: 'Christian Eriksen', number: 10, position: 'Midfielder' },
    { name: 'Mikkel Damsgaard', number: 16, position: 'Forward' },
    { name: 'Kasper Dolberg', number: 20, position: 'Forward' },
    { name: 'Yussuf Poulsen', number: 20, position: 'Forward' },
  ],
  // ─── TURKEY ─────────────────────────────────────────────────────────────────
  Turquía: [
    { name: 'Uğurcan Çakır', number: 1, position: 'Goalkeeper' },
    { name: 'Zeki Çelik', number: 2, position: 'Defender' },
    { name: 'Çağlar Söyüncü', number: 4, position: 'Defender' },
    { name: 'Merih Demiral', number: 3, position: 'Defender' },
    { name: 'Ridvan Yilmaz', number: 13, position: 'Defender' },
    { name: 'Hakan Çalhanoğlu', number: 10, position: 'Midfielder' },
    { name: 'Orkun Kökcü', number: 20, position: 'Midfielder' },
    { name: 'Samet Akaydın', number: 5, position: 'Midfielder' },
    { name: 'Kerem Aktürkoğlu', number: 11, position: 'Forward' },
    { name: 'Baris Alper Yılmaz', number: 7, position: 'Forward' },
    { name: 'Cenk Tosun', number: 9, position: 'Forward' },
  ],
  Turkey: [
    { name: 'Uğurcan Çakır', number: 1, position: 'Goalkeeper' },
    { name: 'Zeki Çelik', number: 2, position: 'Defender' },
    { name: 'Çağlar Söyüncü', number: 4, position: 'Defender' },
    { name: 'Merih Demiral', number: 3, position: 'Defender' },
    { name: 'Ridvan Yilmaz', number: 13, position: 'Defender' },
    { name: 'Hakan Çalhanoğlu', number: 10, position: 'Midfielder' },
    { name: 'Orkun Kökcü', number: 20, position: 'Midfielder' },
    { name: 'Samet Akaydın', number: 5, position: 'Midfielder' },
    { name: 'Kerem Aktürkoğlu', number: 11, position: 'Forward' },
    { name: 'Baris Alper Yılmaz', number: 7, position: 'Forward' },
    { name: 'Cenk Tosun', number: 9, position: 'Forward' },
  ],
  // ─── ECUADOR ────────────────────────────────────────────────────────────────
  Ecuador: [
    { name: 'Hernán Galíndez', number: 1, position: 'Goalkeeper' },
    { name: 'Angelo Preciado', number: 22, position: 'Defender' },
    { name: 'Félix Torres', number: 4, position: 'Defender' },
    { name: 'Piero Hincapié', number: 3, position: 'Defender' },
    { name: 'Pervis Estupiñán', number: 7, position: 'Defender' },
    { name: 'Carlos Gruezo', number: 6, position: 'Midfielder' },
    { name: 'Moisés Caicedo', number: 10, position: 'Midfielder' },
    { name: 'Romario Ibarra', number: 11, position: 'Midfielder' },
    { name: 'Gonzalo Plata', number: 17, position: 'Forward' },
    { name: 'Enner Valencia', number: 13, position: 'Forward' },
    { name: 'Michael Estrada', number: 9, position: 'Forward' },
  ],
};

// ─── Lookup function with fuzzy matching ─────────────────────────────────────
export function getWcSquad(teamName: string): SquadPlayer[] {
  if (!teamName) return [];

  // Direct match first
  if (WC_SQUADS[teamName]) return WC_SQUADS[teamName];

  // Case-insensitive match
  const lower = teamName.toLowerCase();
  const key = Object.keys(WC_SQUADS).find(k => k.toLowerCase() === lower);
  if (key) return WC_SQUADS[key];

  // Partial match (e.g. "R.D. Congo" → "RD Congo", "Rep. Dem. Congo" → "DR Congo")
  const partialKey = Object.keys(WC_SQUADS).find(k => {
    const kLower = k.toLowerCase().replace(/[.\s-]/g, '');
    const nameLower = lower.replace(/[.\s-]/g, '');
    return kLower.includes(nameLower) || nameLower.includes(kLower);
  });
  if (partialKey) return WC_SQUADS[partialKey];

  return [];
}
