// ─── Hardcoded WC 2026 Predicted Starting Lineups ────────────────────────────
// Used as guaranteed fallback when TheSportsDB API and AI both fail to provide lineups.
// Sorted: GK → DEF → MID → FWD

export interface SquadPlayer {
  name: string;
  number: number;
  position: string;
}

const WC_SQUADS: Record<string, SquadPlayer[]> = {
  // ─── PORTUGAL ───────────────────────────────────────────────────────────────
  Portugal: [
    { name: 'Diogo Costa', number: 1, position: 'Goalkeeper' },
    { name: 'João Cancelo', number: 20, position: 'Defender' },
    { name: 'Rúben Dias', number: 6, position: 'Defender' },
    { name: 'António Silva', number: 4, position: 'Defender' },
    { name: 'Nuno Mendes', number: 19, position: 'Defender' },
    { name: 'João Palhinha', number: 26, position: 'Midfielder' },
    { name: 'Vitinha', number: 10, position: 'Midfielder' },
    { name: 'Bruno Fernandes', number: 8, position: 'Midfielder' },
    { name: 'Bernardo Silva', number: 10, position: 'Midfielder' },
    { name: 'Rafael Leão', number: 17, position: 'Forward' },
    { name: 'Cristiano Ronaldo', number: 7, position: 'Forward' },
  ],
  // ─── ESPAÑA ─────────────────────────────────────────────────────────────────
  // WC 2026 squad under De la Fuente (Morata not called up, Busquets/Nacho retired intl.)
  España: [
    { name: 'Unai Simón', number: 1, position: 'Goalkeeper' },
    { name: 'Dani Carvajal', number: 2, position: 'Defender' },
    { name: 'Robin Le Normand', number: 14, position: 'Defender' },
    { name: 'Aymeric Laporte', number: 5, position: 'Defender' },
    { name: 'Marc Cucurella', number: 24, position: 'Defender' },
    { name: 'Rodri', number: 16, position: 'Midfielder' },
    { name: 'Pedri', number: 8, position: 'Midfielder' },
    { name: 'Fabián Ruiz', number: 18, position: 'Midfielder' },
    { name: 'Lamine Yamal', number: 19, position: 'Forward' },
    { name: 'Joselu', number: 9, position: 'Forward' },
    { name: 'Nico Williams', number: 17, position: 'Forward' },
  ],
  // ─── FRANCE ─────────────────────────────────────────────────────────────────
  Francia: [
    { name: 'Mike Maignan', number: 16, position: 'Goalkeeper' },
    { name: 'Jules Koundé', number: 5, position: 'Defender' },
    { name: 'William Saliba', number: 17, position: 'Defender' },
    { name: 'Dayot Upamecano', number: 4, position: 'Defender' },
    { name: 'Theo Hernandez', number: 22, position: 'Defender' },
    { name: 'Aurélien Tchouaméni', number: 8, position: 'Midfielder' },
    { name: 'Eduardo Camavinga', number: 14, position: 'Midfielder' },
    { name: 'Antoine Griezmann', number: 7, position: 'Midfielder' },
    { name: 'Ousmane Dembélé', number: 11, position: 'Forward' },
    { name: 'Kylian Mbappé', number: 10, position: 'Forward' },
    { name: 'Marcus Thuram', number: 9, position: 'Forward' },
  ],
  France: [
    { name: 'Mike Maignan', number: 16, position: 'Goalkeeper' },
    { name: 'Jules Koundé', number: 5, position: 'Defender' },
    { name: 'William Saliba', number: 17, position: 'Defender' },
    { name: 'Dayot Upamecano', number: 4, position: 'Defender' },
    { name: 'Theo Hernandez', number: 22, position: 'Defender' },
    { name: 'Aurélien Tchouaméni', number: 8, position: 'Midfielder' },
    { name: 'Eduardo Camavinga', number: 14, position: 'Midfielder' },
    { name: 'Antoine Griezmann', number: 7, position: 'Midfielder' },
    { name: 'Ousmane Dembélé', number: 11, position: 'Forward' },
    { name: 'Kylian Mbappé', number: 10, position: 'Forward' },
    { name: 'Marcus Thuram', number: 9, position: 'Forward' },
  ],
  // ─── GERMANY ────────────────────────────────────────────────────────────────
  // WC 2026 squad — Rüdiger is Germany captain/defender (NOT Saudi Arabia)
  Alemania: [
    { name: 'Manuel Neuer', number: 1, position: 'Goalkeeper' },
    { name: 'Joshua Kimmich', number: 6, position: 'Defender' },
    { name: 'Antonio Rüdiger', number: 2, position: 'Defender' },
    { name: 'Jonathan Tah', number: 4, position: 'Defender' },
    { name: 'Maximilian Mittelstädt', number: 3, position: 'Defender' },
    { name: 'Ilkay Gündogan', number: 21, position: 'Midfielder' },
    { name: 'Florian Wirtz', number: 10, position: 'Midfielder' },
    { name: 'Jamal Musiala', number: 14, position: 'Midfielder' },
    { name: 'Leroy Sané', number: 19, position: 'Forward' },
    { name: 'Kai Havertz', number: 7, position: 'Forward' },
    { name: 'Deniz Undav', number: 9, position: 'Forward' },
  ],
  Germany: [
    { name: 'Manuel Neuer', number: 1, position: 'Goalkeeper' },
    { name: 'Joshua Kimmich', number: 6, position: 'Defender' },
    { name: 'Antonio Rüdiger', number: 2, position: 'Defender' },
    { name: 'Jonathan Tah', number: 4, position: 'Defender' },
    { name: 'Maximilian Mittelstädt', number: 3, position: 'Defender' },
    { name: 'Ilkay Gündogan', number: 21, position: 'Midfielder' },
    { name: 'Florian Wirtz', number: 10, position: 'Midfielder' },
    { name: 'Jamal Musiala', number: 14, position: 'Midfielder' },
    { name: 'Leroy Sané', number: 19, position: 'Forward' },
    { name: 'Kai Havertz', number: 7, position: 'Forward' },
    { name: 'Deniz Undav', number: 9, position: 'Forward' },
  ],
  // ─── BRASIL ─────────────────────────────────────────────────────────────────
  Brasil: [
    { name: 'Alisson', number: 1, position: 'Goalkeeper' },
    { name: 'Danilo', number: 2, position: 'Defender' },
    { name: 'Éder Militão', number: 3, position: 'Defender' },
    { name: 'Marquinhos', number: 4, position: 'Defender' },
    { name: 'Guilherme Arana', number: 6, position: 'Defender' },
    { name: 'Casemiro', number: 5, position: 'Midfielder' },
    { name: 'Lucas Paquetá', number: 10, position: 'Midfielder' },
    { name: 'Bruno Guimarães', number: 18, position: 'Midfielder' },
    { name: 'Rodrygo', number: 11, position: 'Forward' },
    { name: 'Vinicius Jr', number: 7, position: 'Forward' },
    { name: 'Raphinha', number: 19, position: 'Forward' },
  ],
  Brazil: [
    { name: 'Alisson', number: 1, position: 'Goalkeeper' },
    { name: 'Danilo', number: 2, position: 'Defender' },
    { name: 'Éder Militão', number: 3, position: 'Defender' },
    { name: 'Marquinhos', number: 4, position: 'Defender' },
    { name: 'Guilherme Arana', number: 6, position: 'Defender' },
    { name: 'Casemiro', number: 5, position: 'Midfielder' },
    { name: 'Lucas Paquetá', number: 10, position: 'Midfielder' },
    { name: 'Bruno Guimarães', number: 18, position: 'Midfielder' },
    { name: 'Rodrygo', number: 11, position: 'Forward' },
    { name: 'Vinicius Jr', number: 7, position: 'Forward' },
    { name: 'Raphinha', number: 19, position: 'Forward' },
  ],
  // ─── ARGENTINA ──────────────────────────────────────────────────────────────
  Argentina: [
    { name: 'E. Martínez', number: 23, position: 'Goalkeeper' },
    { name: 'Nahuel Molina', number: 26, position: 'Defender' },
    { name: 'Cristian Romero', number: 13, position: 'Defender' },
    { name: 'Nicolás Otamendi', number: 19, position: 'Defender' },
    { name: 'Marcos Acuña', number: 8, position: 'Defender' },
    { name: 'Rodrigo De Paul', number: 7, position: 'Midfielder' },
    { name: 'Leandro Paredes', number: 5, position: 'Midfielder' },
    { name: 'Alexis Mac Allister', number: 20, position: 'Midfielder' },
    { name: 'Lionel Messi', number: 10, position: 'Forward' },
    { name: 'Lautaro Martínez', number: 22, position: 'Forward' },
    { name: 'Julián Álvarez', number: 9, position: 'Forward' },
  ],
  // ─── ENGLAND ────────────────────────────────────────────────────────────────
  Inglaterra: [
    { name: 'Jordan Pickford', number: 1, position: 'Goalkeeper' },
    { name: 'Trent Alexander-Arnold', number: 66, position: 'Defender' },
    { name: 'John Stones', number: 5, position: 'Defender' },
    { name: 'Harry Maguire', number: 6, position: 'Defender' },
    { name: 'Luke Shaw', number: 3, position: 'Defender' },
    { name: 'Declan Rice', number: 4, position: 'Midfielder' },
    { name: 'Jude Bellingham', number: 22, position: 'Midfielder' },
    { name: 'Phil Foden', number: 47, position: 'Midfielder' },
    { name: 'Bukayo Saka', number: 17, position: 'Forward' },
    { name: 'Harry Kane', number: 9, position: 'Forward' },
    { name: 'Marcus Rashford', number: 11, position: 'Forward' },
  ],
  England: [
    { name: 'Jordan Pickford', number: 1, position: 'Goalkeeper' },
    { name: 'Trent Alexander-Arnold', number: 66, position: 'Defender' },
    { name: 'John Stones', number: 5, position: 'Defender' },
    { name: 'Harry Maguire', number: 6, position: 'Defender' },
    { name: 'Luke Shaw', number: 3, position: 'Defender' },
    { name: 'Declan Rice', number: 4, position: 'Midfielder' },
    { name: 'Jude Bellingham', number: 22, position: 'Midfielder' },
    { name: 'Phil Foden', number: 47, position: 'Midfielder' },
    { name: 'Bukayo Saka', number: 17, position: 'Forward' },
    { name: 'Harry Kane', number: 9, position: 'Forward' },
    { name: 'Marcus Rashford', number: 11, position: 'Forward' },
  ],
  // ─── NETHERLANDS ────────────────────────────────────────────────────────────
  Holanda: [
    { name: 'Bart Verbruggen', number: 1, position: 'Goalkeeper' },
    { name: 'Denzel Dumfries', number: 22, position: 'Defender' },
    { name: 'Virgil van Dijk', number: 4, position: 'Defender' },
    { name: 'Matthijs de Ligt', number: 3, position: 'Defender' },
    { name: 'Nathan Aké', number: 5, position: 'Defender' },
    { name: 'Frenkie de Jong', number: 21, position: 'Midfielder' },
    { name: 'Tijjani Reijnders', number: 8, position: 'Midfielder' },
    { name: 'Xavi Simons', number: 10, position: 'Midfielder' },
    { name: 'Cody Gakpo', number: 11, position: 'Forward' },
    { name: 'Memphis Depay', number: 9, position: 'Forward' },
    { name: 'Donyell Malen', number: 7, position: 'Forward' },
  ],
  Netherlands: [
    { name: 'Bart Verbruggen', number: 1, position: 'Goalkeeper' },
    { name: 'Denzel Dumfries', number: 22, position: 'Defender' },
    { name: 'Virgil van Dijk', number: 4, position: 'Defender' },
    { name: 'Matthijs de Ligt', number: 3, position: 'Defender' },
    { name: 'Nathan Aké', number: 5, position: 'Defender' },
    { name: 'Frenkie de Jong', number: 21, position: 'Midfielder' },
    { name: 'Tijjani Reijnders', number: 8, position: 'Midfielder' },
    { name: 'Xavi Simons', number: 10, position: 'Midfielder' },
    { name: 'Cody Gakpo', number: 11, position: 'Forward' },
    { name: 'Memphis Depay', number: 9, position: 'Forward' },
    { name: 'Donyell Malen', number: 7, position: 'Forward' },
  ],
  // ─── MOROCCO ────────────────────────────────────────────────────────────────
  Marruecos: [
    { name: 'Bono', number: 1, position: 'Goalkeeper' },
    { name: 'Achraf Hakimi', number: 2, position: 'Defender' },
    { name: 'Nayef Aguerd', number: 5, position: 'Defender' },
    { name: 'Romain Saïss', number: 21, position: 'Defender' },
    { name: 'Noussair Mazraoui', number: 3, position: 'Defender' },
    { name: 'Sofyan Amrabat', number: 4, position: 'Midfielder' },
    { name: 'Azzedine Ounahi', number: 8, position: 'Midfielder' },
    { name: 'Hakim Ziyech', number: 7, position: 'Midfielder' },
    { name: 'Sofiane Boufal', number: 11, position: 'Forward' },
    { name: 'Youssef En-Nesyri', number: 19, position: 'Forward' },
    { name: 'Walid Cheddira', number: 9, position: 'Forward' },
  ],
  Morocco: [
    { name: 'Bono', number: 1, position: 'Goalkeeper' },
    { name: 'Achraf Hakimi', number: 2, position: 'Defender' },
    { name: 'Nayef Aguerd', number: 5, position: 'Defender' },
    { name: 'Romain Saïss', number: 21, position: 'Defender' },
    { name: 'Noussair Mazraoui', number: 3, position: 'Defender' },
    { name: 'Sofyan Amrabat', number: 4, position: 'Midfielder' },
    { name: 'Azzedine Ounahi', number: 8, position: 'Midfielder' },
    { name: 'Hakim Ziyech', number: 7, position: 'Midfielder' },
    { name: 'Sofiane Boufal', number: 11, position: 'Forward' },
    { name: 'Youssef En-Nesyri', number: 19, position: 'Forward' },
    { name: 'Walid Cheddira', number: 9, position: 'Forward' },
  ],
  // ─── USA ────────────────────────────────────────────────────────────────────
  USA: [
    { name: 'Matt Turner', number: 1, position: 'Goalkeeper' },
    { name: 'Sergino Dest', number: 2, position: 'Defender' },
    { name: 'Miles Robinson', number: 12, position: 'Defender' },
    { name: 'Walker Zimmerman', number: 3, position: 'Defender' },
    { name: 'Antonee Robinson', number: 5, position: 'Defender' },
    { name: 'Tyler Adams', number: 4, position: 'Midfielder' },
    { name: 'Weston McKennie', number: 8, position: 'Midfielder' },
    { name: 'Christian Pulisic', number: 10, position: 'Midfielder' },
    { name: 'Giovanni Reyna', number: 7, position: 'Forward' },
    { name: 'Josh Sargent', number: 9, position: 'Forward' },
    { name: 'Tim Weah', number: 21, position: 'Forward' },
  ],
  'Estados Unidos': [
    { name: 'Matt Turner', number: 1, position: 'Goalkeeper' },
    { name: 'Sergino Dest', number: 2, position: 'Defender' },
    { name: 'Miles Robinson', number: 12, position: 'Defender' },
    { name: 'Walker Zimmerman', number: 3, position: 'Defender' },
    { name: 'Antonee Robinson', number: 5, position: 'Defender' },
    { name: 'Tyler Adams', number: 4, position: 'Midfielder' },
    { name: 'Weston McKennie', number: 8, position: 'Midfielder' },
    { name: 'Christian Pulisic', number: 10, position: 'Midfielder' },
    { name: 'Giovanni Reyna', number: 7, position: 'Forward' },
    { name: 'Josh Sargent', number: 9, position: 'Forward' },
    { name: 'Tim Weah', number: 21, position: 'Forward' },
  ],
  // ─── MEXICO ─────────────────────────────────────────────────────────────────
  México: [
    { name: 'Guillermo Ochoa', number: 13, position: 'Goalkeeper' },
    { name: 'Jorge Sánchez', number: 2, position: 'Defender' },
    { name: 'Nestor Araujo', number: 4, position: 'Defender' },
    { name: 'Johan Vásquez', number: 15, position: 'Defender' },
    { name: 'Jesús Gallardo', number: 3, position: 'Defender' },
    { name: 'Edson Álvarez', number: 18, position: 'Midfielder' },
    { name: 'Carlos Rodríguez', number: 7, position: 'Midfielder' },
    { name: 'Héctor Herrera', number: 16, position: 'Midfielder' },
    { name: 'Hirving Lozano', number: 22, position: 'Forward' },
    { name: 'Santiago Giménez', number: 9, position: 'Forward' },
    { name: 'Henry Martín', number: 14, position: 'Forward' },
  ],
  Mexico: [
    { name: 'Guillermo Ochoa', number: 13, position: 'Goalkeeper' },
    { name: 'Jorge Sánchez', number: 2, position: 'Defender' },
    { name: 'Nestor Araujo', number: 4, position: 'Defender' },
    { name: 'Johan Vásquez', number: 15, position: 'Defender' },
    { name: 'Jesús Gallardo', number: 3, position: 'Defender' },
    { name: 'Edson Álvarez', number: 18, position: 'Midfielder' },
    { name: 'Carlos Rodríguez', number: 7, position: 'Midfielder' },
    { name: 'Héctor Herrera', number: 16, position: 'Midfielder' },
    { name: 'Hirving Lozano', number: 22, position: 'Forward' },
    { name: 'Santiago Giménez', number: 9, position: 'Forward' },
    { name: 'Henry Martín', number: 14, position: 'Forward' },
  ],
  // ─── CANADA ─────────────────────────────────────────────────────────────────
  Canadá: [
    { name: 'Milan Borjan', number: 18, position: 'Goalkeeper' },
    { name: 'Alistair Johnston', number: 2, position: 'Defender' },
    { name: 'Kamal Miller', number: 3, position: 'Defender' },
    { name: 'Derek Cornelius', number: 4, position: 'Defender' },
    { name: 'Richie Laryea', number: 22, position: 'Defender' },
    { name: 'Atiba Hutchinson', number: 13, position: 'Midfielder' },
    { name: 'Stephen Eustáquio', number: 7, position: 'Midfielder' },
    { name: 'Jonathan Osorio', number: 21, position: 'Midfielder' },
    { name: 'Alphonso Davies', number: 19, position: 'Forward' },
    { name: 'Jonathan David', number: 20, position: 'Forward' },
    { name: 'Tajon Buchanan', number: 11, position: 'Forward' },
  ],
  Canada: [
    { name: 'Milan Borjan', number: 18, position: 'Goalkeeper' },
    { name: 'Alistair Johnston', number: 2, position: 'Defender' },
    { name: 'Kamal Miller', number: 3, position: 'Defender' },
    { name: 'Derek Cornelius', number: 4, position: 'Defender' },
    { name: 'Richie Laryea', number: 22, position: 'Defender' },
    { name: 'Atiba Hutchinson', number: 13, position: 'Midfielder' },
    { name: 'Stephen Eustáquio', number: 7, position: 'Midfielder' },
    { name: 'Jonathan Osorio', number: 21, position: 'Midfielder' },
    { name: 'Alphonso Davies', number: 19, position: 'Forward' },
    { name: 'Jonathan David', number: 20, position: 'Forward' },
    { name: 'Tajon Buchanan', number: 11, position: 'Forward' },
  ],
  // ─── JAPAN ──────────────────────────────────────────────────────────────────
  Japón: [
    { name: 'Shuichi Gonda', number: 12, position: 'Goalkeeper' },
    { name: 'Hiroki Sakai', number: 5, position: 'Defender' },
    { name: 'Ko Itakura', number: 16, position: 'Defender' },
    { name: 'Maya Yoshida', number: 22, position: 'Defender' },
    { name: 'Yuto Nagatomo', number: 6, position: 'Defender' },
    { name: 'Wataru Endo', number: 17, position: 'Midfielder' },
    { name: 'Hidemasa Morita', number: 10, position: 'Midfielder' },
    { name: 'Daichi Kamada', number: 14, position: 'Midfielder' },
    { name: 'Junya Ito', number: 19, position: 'Forward' },
    { name: 'Kaoru Mitoma', number: 11, position: 'Forward' },
    { name: 'Takumi Minamino', number: 9, position: 'Forward' },
  ],
  Japan: [
    { name: 'Shuichi Gonda', number: 12, position: 'Goalkeeper' },
    { name: 'Hiroki Sakai', number: 5, position: 'Defender' },
    { name: 'Ko Itakura', number: 16, position: 'Defender' },
    { name: 'Maya Yoshida', number: 22, position: 'Defender' },
    { name: 'Yuto Nagatomo', number: 6, position: 'Defender' },
    { name: 'Wataru Endo', number: 17, position: 'Midfielder' },
    { name: 'Hidemasa Morita', number: 10, position: 'Midfielder' },
    { name: 'Daichi Kamada', number: 14, position: 'Midfielder' },
    { name: 'Junya Ito', number: 19, position: 'Forward' },
    { name: 'Kaoru Mitoma', number: 11, position: 'Forward' },
    { name: 'Takumi Minamino', number: 9, position: 'Forward' },
  ],
  // ─── CROATIA ────────────────────────────────────────────────────────────────
  // WC 2026 — Perišić retired from national team after ACL injury
  Croacia: [
    { name: 'Dominik Livaković', number: 1, position: 'Goalkeeper' },
    { name: 'Josip Stanišić', number: 17, position: 'Defender' },
    { name: 'Joško Gvardiol', number: 3, position: 'Defender' },
    { name: 'Martin Erlić', number: 6, position: 'Defender' },
    { name: 'Borna Sosa', number: 15, position: 'Defender' },
    { name: 'Luka Modrić', number: 10, position: 'Midfielder' },
    { name: 'Marcelo Brozović', number: 11, position: 'Midfielder' },
    { name: 'Mateo Kovačić', number: 8, position: 'Midfielder' },
    { name: 'Luka Ivanušec', number: 14, position: 'Forward' },
    { name: 'Andrej Kramarić', number: 9, position: 'Forward' },
    { name: 'Bruno Petković', number: 16, position: 'Forward' },
  ],
  Croatia: [
    { name: 'Dominik Livaković', number: 1, position: 'Goalkeeper' },
    { name: 'Josip Stanišić', number: 17, position: 'Defender' },
    { name: 'Joško Gvardiol', number: 3, position: 'Defender' },
    { name: 'Martin Erlić', number: 6, position: 'Defender' },
    { name: 'Borna Sosa', number: 15, position: 'Defender' },
    { name: 'Luka Modrić', number: 10, position: 'Midfielder' },
    { name: 'Marcelo Brozović', number: 11, position: 'Midfielder' },
    { name: 'Mateo Kovačić', number: 8, position: 'Midfielder' },
    { name: 'Luka Ivanušec', number: 14, position: 'Forward' },
    { name: 'Andrej Kramarić', number: 9, position: 'Forward' },
    { name: 'Bruno Petković', number: 16, position: 'Forward' },
  ],
  // ─── SENEGAL ────────────────────────────────────────────────────────────────
  Senegal: [
    { name: 'Édouard Mendy', number: 16, position: 'Goalkeeper' },
    { name: 'Youssouf Sabaly', number: 2, position: 'Defender' },
    { name: 'Kalidou Koulibaly', number: 3, position: 'Defender' },
    { name: 'Abdou Diallo', number: 5, position: 'Defender' },
    { name: 'Formose Mendy', number: 23, position: 'Defender' },
    { name: 'Idrissa Gueye', number: 17, position: 'Midfielder' },
    { name: 'Pape Gueye', number: 8, position: 'Midfielder' },
    { name: 'Nampalys Mendy', number: 6, position: 'Midfielder' },
    { name: 'Sadio Mané', number: 10, position: 'Forward' },
    { name: 'Ismaila Sarr', number: 19, position: 'Forward' },
    { name: 'Boulaye Dia', number: 9, position: 'Forward' },
  ],
  // ─── SWITZERLAND ────────────────────────────────────────────────────────────
  Suiza: [
    { name: 'Yann Sommer', number: 1, position: 'Goalkeeper' },
    { name: 'Silvan Widmer', number: 3, position: 'Defender' },
    { name: 'Manuel Akanji', number: 5, position: 'Defender' },
    { name: 'Fabian Schär', number: 4, position: 'Defender' },
    { name: 'Ricardo Rodríguez', number: 13, position: 'Defender' },
    { name: 'Granit Xhaka', number: 10, position: 'Midfielder' },
    { name: 'Remo Freuler', number: 23, position: 'Midfielder' },
    { name: 'Denis Zakaria', number: 8, position: 'Midfielder' },
    { name: 'Xherdan Shaqiri', number: 23, position: 'Forward' },
    { name: 'Breel Embolo', number: 7, position: 'Forward' },
    { name: 'Ruben Vargas', number: 16, position: 'Forward' },
  ],
  Switzerland: [
    { name: 'Yann Sommer', number: 1, position: 'Goalkeeper' },
    { name: 'Silvan Widmer', number: 3, position: 'Defender' },
    { name: 'Manuel Akanji', number: 5, position: 'Defender' },
    { name: 'Fabian Schär', number: 4, position: 'Defender' },
    { name: 'Ricardo Rodríguez', number: 13, position: 'Defender' },
    { name: 'Granit Xhaka', number: 10, position: 'Midfielder' },
    { name: 'Remo Freuler', number: 23, position: 'Midfielder' },
    { name: 'Denis Zakaria', number: 8, position: 'Midfielder' },
    { name: 'Xherdan Shaqiri', number: 23, position: 'Forward' },
    { name: 'Breel Embolo', number: 7, position: 'Forward' },
    { name: 'Ruben Vargas', number: 16, position: 'Forward' },
  ],
  // ─── BELGIUM ────────────────────────────────────────────────────────────────
  // WC 2026 — Hazard/Witsel/Alderweireld/Vertonghen all retired from national team
  Bélgica: [
    { name: 'Thibaut Courtois', number: 1, position: 'Goalkeeper' },
    { name: 'Timothy Castagne', number: 2, position: 'Defender' },
    { name: 'Wout Faes', number: 4, position: 'Defender' },
    { name: 'Zeno Debast', number: 5, position: 'Defender' },
    { name: 'Arthur Theate', number: 3, position: 'Defender' },
    { name: 'Kevin De Bruyne', number: 7, position: 'Midfielder' },
    { name: 'Youri Tielemans', number: 8, position: 'Midfielder' },
    { name: 'Orel Mangala', number: 6, position: 'Midfielder' },
    { name: 'Leandro Trossard', number: 19, position: 'Forward' },
    { name: 'Romelu Lukaku', number: 9, position: 'Forward' },
    { name: 'Lois Openda', number: 11, position: 'Forward' },
  ],
  Belgium: [
    { name: 'Thibaut Courtois', number: 1, position: 'Goalkeeper' },
    { name: 'Timothy Castagne', number: 2, position: 'Defender' },
    { name: 'Wout Faes', number: 4, position: 'Defender' },
    { name: 'Zeno Debast', number: 5, position: 'Defender' },
    { name: 'Arthur Theate', number: 3, position: 'Defender' },
    { name: 'Kevin De Bruyne', number: 7, position: 'Midfielder' },
    { name: 'Youri Tielemans', number: 8, position: 'Midfielder' },
    { name: 'Orel Mangala', number: 6, position: 'Midfielder' },
    { name: 'Leandro Trossard', number: 19, position: 'Forward' },
    { name: 'Romelu Lukaku', number: 9, position: 'Forward' },
    { name: 'Lois Openda', number: 11, position: 'Forward' },
  ],
  // ─── URUGUAY ────────────────────────────────────────────────────────────────
  // WC 2026 — Godín retired intl. 2022, Suárez no longer regularly called up
  Uruguay: [
    { name: 'Sergio Rochet', number: 1, position: 'Goalkeeper' },
    { name: 'Nahitan Nández', number: 4, position: 'Defender' },
    { name: 'José María Giménez', number: 2, position: 'Defender' },
    { name: 'Ronald Araújo', number: 5, position: 'Defender' },
    { name: 'Mathías Olivera', number: 22, position: 'Defender' },
    { name: 'Rodrigo Bentancur', number: 6, position: 'Midfielder' },
    { name: 'Lucas Torreira', number: 8, position: 'Midfielder' },
    { name: 'Federico Valverde', number: 14, position: 'Midfielder' },
    { name: 'Darwin Núñez', number: 11, position: 'Forward' },
    { name: 'Maximiliano Araújo', number: 10, position: 'Forward' },
    { name: 'Facundo Torres', number: 21, position: 'Forward' },
  ],
  // ─── COLOMBIA ───────────────────────────────────────────────────────────────
  // WC 2026 — Falcao retired, updated squad under Néstor Lorenzo
  Colombia: [
    { name: 'Camilo Vargas', number: 1, position: 'Goalkeeper' },
    { name: 'Daniel Muñoz', number: 2, position: 'Defender' },
    { name: 'Dávinson Sánchez', number: 6, position: 'Defender' },
    { name: 'Jhon Lucumí', number: 3, position: 'Defender' },
    { name: 'Johan Mojica', number: 16, position: 'Defender' },
    { name: 'Richard Ríos', number: 5, position: 'Midfielder' },
    { name: 'Jefferson Lerma', number: 8, position: 'Midfielder' },
    { name: 'James Rodríguez', number: 10, position: 'Midfielder' },
    { name: 'Luis Díaz', number: 23, position: 'Forward' },
    { name: 'Jhon Córdoba', number: 9, position: 'Forward' },
    { name: 'Rafael Santos Borré', number: 19, position: 'Forward' },
  ],
  // ─── DR CONGO ───────────────────────────────────────────────────────────────
  'R.D. Congo': [
    { name: 'Joël Kiassumbua', number: 1, position: 'Goalkeeper' },
    { name: 'Chancel Mbemba', number: 5, position: 'Defender' },
    { name: 'Marcel Tisserand', number: 4, position: 'Defender' },
    { name: 'Arthur Masuaku', number: 3, position: 'Defender' },
    { name: 'Dylan Batubinsika', number: 23, position: 'Defender' },
    { name: 'Paul-José Mpoku', number: 10, position: 'Midfielder' },
    { name: 'Yannick Bolasie', number: 7, position: 'Midfielder' },
    { name: 'Théo Bongonda', number: 11, position: 'Midfielder' },
    { name: 'Cédric Bakambu', number: 9, position: 'Forward' },
    { name: 'Silas Mvumpa', number: 17, position: 'Forward' },
    { name: 'Dieumerci Mbokani', number: 21, position: 'Forward' },
  ],
  'RD Congo': [
    { name: 'Joël Kiassumbua', number: 1, position: 'Goalkeeper' },
    { name: 'Chancel Mbemba', number: 5, position: 'Defender' },
    { name: 'Marcel Tisserand', number: 4, position: 'Defender' },
    { name: 'Arthur Masuaku', number: 3, position: 'Defender' },
    { name: 'Dylan Batubinsika', number: 23, position: 'Defender' },
    { name: 'Paul-José Mpoku', number: 10, position: 'Midfielder' },
    { name: 'Yannick Bolasie', number: 7, position: 'Midfielder' },
    { name: 'Théo Bongonda', number: 11, position: 'Midfielder' },
    { name: 'Cédric Bakambu', number: 9, position: 'Forward' },
    { name: 'Silas Mvumpa', number: 17, position: 'Forward' },
    { name: 'Dieumerci Mbokani', number: 21, position: 'Forward' },
  ],
  'DR Congo': [
    { name: 'Joël Kiassumbua', number: 1, position: 'Goalkeeper' },
    { name: 'Chancel Mbemba', number: 5, position: 'Defender' },
    { name: 'Marcel Tisserand', number: 4, position: 'Defender' },
    { name: 'Arthur Masuaku', number: 3, position: 'Defender' },
    { name: 'Dylan Batubinsika', number: 23, position: 'Defender' },
    { name: 'Paul-José Mpoku', number: 10, position: 'Midfielder' },
    { name: 'Yannick Bolasie', number: 7, position: 'Midfielder' },
    { name: 'Théo Bongonda', number: 11, position: 'Midfielder' },
    { name: 'Cédric Bakambu', number: 9, position: 'Forward' },
    { name: 'Silas Mvumpa', number: 17, position: 'Forward' },
    { name: 'Dieumerci Mbokani', number: 21, position: 'Forward' },
  ],
  'Rep. Dem. Congo': [
    { name: 'Joël Kiassumbua', number: 1, position: 'Goalkeeper' },
    { name: 'Chancel Mbemba', number: 5, position: 'Defender' },
    { name: 'Marcel Tisserand', number: 4, position: 'Defender' },
    { name: 'Arthur Masuaku', number: 3, position: 'Defender' },
    { name: 'Dylan Batubinsika', number: 23, position: 'Defender' },
    { name: 'Paul-José Mpoku', number: 10, position: 'Midfielder' },
    { name: 'Yannick Bolasie', number: 7, position: 'Midfielder' },
    { name: 'Théo Bongonda', number: 11, position: 'Midfielder' },
    { name: 'Cédric Bakambu', number: 9, position: 'Forward' },
    { name: 'Silas Mvumpa', number: 17, position: 'Forward' },
    { name: 'Dieumerci Mbokani', number: 21, position: 'Forward' },
  ],
  'Congo, DR': [
    { name: 'Joël Kiassumbua', number: 1, position: 'Goalkeeper' },
    { name: 'Chancel Mbemba', number: 5, position: 'Defender' },
    { name: 'Marcel Tisserand', number: 4, position: 'Defender' },
    { name: 'Arthur Masuaku', number: 3, position: 'Defender' },
    { name: 'Dylan Batubinsika', number: 23, position: 'Defender' },
    { name: 'Paul-José Mpoku', number: 10, position: 'Midfielder' },
    { name: 'Yannick Bolasie', number: 7, position: 'Midfielder' },
    { name: 'Théo Bongonda', number: 11, position: 'Midfielder' },
    { name: 'Cédric Bakambu', number: 9, position: 'Forward' },
    { name: 'Silas Mvumpa', number: 17, position: 'Forward' },
    { name: 'Dieumerci Mbokani', number: 21, position: 'Forward' },
  ],
  // ─── CAPE VERDE ─────────────────────────────────────────────────────────────
  'Cabo Verde': [
    { name: 'Vozinha', number: 1, position: 'Goalkeeper' },
    { name: 'Stopira', number: 4, position: 'Defender' },
    { name: 'Filho', number: 5, position: 'Defender' },
    { name: 'Bryan Teixeira', number: 3, position: 'Defender' },
    { name: 'Steven Fortes', number: 2, position: 'Defender' },
    { name: 'Garry Rodrigues', number: 7, position: 'Midfielder' },
    { name: 'Ryan Mendes', number: 10, position: 'Midfielder' },
    { name: 'Kenny Rocha', number: 6, position: 'Midfielder' },
    { name: 'Fali', number: 8, position: 'Midfielder' },
    { name: 'Djaniny', number: 9, position: 'Forward' },
    { name: 'Jovane Cabral', number: 11, position: 'Forward' },
  ],
  'Cape Verde': [
    { name: 'Vozinha', number: 1, position: 'Goalkeeper' },
    { name: 'Stopira', number: 4, position: 'Defender' },
    { name: 'Filho', number: 5, position: 'Defender' },
    { name: 'Bryan Teixeira', number: 3, position: 'Defender' },
    { name: 'Steven Fortes', number: 2, position: 'Defender' },
    { name: 'Garry Rodrigues', number: 7, position: 'Midfielder' },
    { name: 'Ryan Mendes', number: 10, position: 'Midfielder' },
    { name: 'Kenny Rocha', number: 6, position: 'Midfielder' },
    { name: 'Fali', number: 8, position: 'Midfielder' },
    { name: 'Djaniny', number: 9, position: 'Forward' },
    { name: 'Jovane Cabral', number: 11, position: 'Forward' },
  ],
  // ─── SOUTH AFRICA ───────────────────────────────────────────────────────────
  Sudáfrica: [
    { name: 'Ronwen Williams', number: 1, position: 'Goalkeeper' },
    { name: 'Reeve Frosler', number: 2, position: 'Defender' },
    { name: 'Rushine De Reuck', number: 4, position: 'Defender' },
    { name: 'Mothobi Mvala', number: 5, position: 'Defender' },
    { name: 'Sifiso Hlanti', number: 3, position: 'Defender' },
    { name: 'Ethan Ntshumayelo', number: 6, position: 'Midfielder' },
    { name: 'Themba Zwane', number: 10, position: 'Midfielder' },
    { name: 'Bongani Zungu', number: 8, position: 'Midfielder' },
    { name: 'Percy Tau', number: 7, position: 'Forward' },
    { name: 'Lyle Foster', number: 9, position: 'Forward' },
    { name: 'Lebo Mothiba', number: 11, position: 'Forward' },
  ],
  'South Africa': [
    { name: 'Ronwen Williams', number: 1, position: 'Goalkeeper' },
    { name: 'Reeve Frosler', number: 2, position: 'Defender' },
    { name: 'Rushine De Reuck', number: 4, position: 'Defender' },
    { name: 'Mothobi Mvala', number: 5, position: 'Defender' },
    { name: 'Sifiso Hlanti', number: 3, position: 'Defender' },
    { name: 'Ethan Ntshumayelo', number: 6, position: 'Midfielder' },
    { name: 'Themba Zwane', number: 10, position: 'Midfielder' },
    { name: 'Bongani Zungu', number: 8, position: 'Midfielder' },
    { name: 'Percy Tau', number: 7, position: 'Forward' },
    { name: 'Lyle Foster', number: 9, position: 'Forward' },
    { name: 'Lebo Mothiba', number: 11, position: 'Forward' },
  ],
  // ─── UZBEKISTAN ─────────────────────────────────────────────────────────────
  Uzbekistán: [
    { name: 'Utkir Yusupov', number: 1, position: 'Goalkeeper' },
    { name: 'Sanjar Tursunov', number: 2, position: 'Defender' },
    { name: 'Khojiakbar Alijonov', number: 4, position: 'Defender' },
    { name: 'Jasurbek Yakhshiboev', number: 5, position: 'Defender' },
    { name: 'Sherzod Nishonov', number: 3, position: 'Defender' },
    { name: 'Jaloliddin Masharipov', number: 10, position: 'Midfielder' },
    { name: 'Odiljon Hamrobekov', number: 8, position: 'Midfielder' },
    { name: 'Otabek Shukurov', number: 6, position: 'Midfielder' },
    { name: 'Eldor Shomurodov', number: 9, position: 'Forward' },
    { name: 'Islom Tukhtahujaev', number: 11, position: 'Forward' },
    { name: 'Dostonbek Khamdamov', number: 7, position: 'Forward' },
  ],
  Uzbekistan: [
    { name: 'Utkir Yusupov', number: 1, position: 'Goalkeeper' },
    { name: 'Sanjar Tursunov', number: 2, position: 'Defender' },
    { name: 'Khojiakbar Alijonov', number: 4, position: 'Defender' },
    { name: 'Jasurbek Yakhshiboev', number: 5, position: 'Defender' },
    { name: 'Sherzod Nishonov', number: 3, position: 'Defender' },
    { name: 'Jaloliddin Masharipov', number: 10, position: 'Midfielder' },
    { name: 'Odiljon Hamrobekov', number: 8, position: 'Midfielder' },
    { name: 'Otabek Shukurov', number: 6, position: 'Midfielder' },
    { name: 'Eldor Shomurodov', number: 9, position: 'Forward' },
    { name: 'Islom Tukhtahujaev', number: 11, position: 'Forward' },
    { name: 'Dostonbek Khamdamov', number: 7, position: 'Forward' },
  ],
  // ─── ALGERIA ────────────────────────────────────────────────────────────────
  Argelia: [
    { name: 'Raïs M\'Bolhi', number: 1, position: 'Goalkeeper' },
    { name: 'Youcef Atal', number: 2, position: 'Defender' },
    { name: 'Djamel Benlamri', number: 4, position: 'Defender' },
    { name: 'Ramy Bensebaïni', number: 3, position: 'Defender' },
    { name: 'Aïssa Mandi', number: 5, position: 'Defender' },
    { name: 'Nabil Bentaleb', number: 8, position: 'Midfielder' },
    { name: 'Sofiane Feghouli', number: 18, position: 'Midfielder' },
    { name: 'Nacer Chabli', number: 6, position: 'Midfielder' },
    { name: 'Riyad Mahrez', number: 7, position: 'Forward' },
    { name: 'Islam Slimani', number: 9, position: 'Forward' },
    { name: 'Yacine Brahimi', number: 10, position: 'Forward' },
  ],
  Algeria: [
    { name: 'Raïs M\'Bolhi', number: 1, position: 'Goalkeeper' },
    { name: 'Youcef Atal', number: 2, position: 'Defender' },
    { name: 'Djamel Benlamri', number: 4, position: 'Defender' },
    { name: 'Ramy Bensebaïni', number: 3, position: 'Defender' },
    { name: 'Aïssa Mandi', number: 5, position: 'Defender' },
    { name: 'Nabil Bentaleb', number: 8, position: 'Midfielder' },
    { name: 'Sofiane Feghouli', number: 18, position: 'Midfielder' },
    { name: 'Nacer Chabli', number: 6, position: 'Midfielder' },
    { name: 'Riyad Mahrez', number: 7, position: 'Forward' },
    { name: 'Islam Slimani', number: 9, position: 'Forward' },
    { name: 'Yacine Brahimi', number: 10, position: 'Forward' },
  ],
  // ─── POLAND ─────────────────────────────────────────────────────────────────
  Polonia: [
    { name: 'Wojciech Szczęsny', number: 1, position: 'Goalkeeper' },
    { name: 'Matty Cash', number: 2, position: 'Defender' },
    { name: 'Jan Bednarek', number: 5, position: 'Defender' },
    { name: 'Kamil Glik', number: 15, position: 'Defender' },
    { name: 'Nicola Zalewski', number: 17, position: 'Defender' },
    { name: 'Krzysztof Piątek', number: 7, position: 'Midfielder' },
    { name: 'Grzegorz Krychowiak', number: 10, position: 'Midfielder' },
    { name: 'Piotr Zieliński', number: 20, position: 'Midfielder' },
    { name: 'Kamil Grosicki', number: 11, position: 'Forward' },
    { name: 'Robert Lewandowski', number: 9, position: 'Forward' },
    { name: 'Arkadiusz Milik', number: 23, position: 'Forward' },
  ],
  Poland: [
    { name: 'Wojciech Szczęsny', number: 1, position: 'Goalkeeper' },
    { name: 'Matty Cash', number: 2, position: 'Defender' },
    { name: 'Jan Bednarek', number: 5, position: 'Defender' },
    { name: 'Kamil Glik', number: 15, position: 'Defender' },
    { name: 'Nicola Zalewski', number: 17, position: 'Defender' },
    { name: 'Krzysztof Piątek', number: 7, position: 'Midfielder' },
    { name: 'Grzegorz Krychowiak', number: 10, position: 'Midfielder' },
    { name: 'Piotr Zieliński', number: 20, position: 'Midfielder' },
    { name: 'Kamil Grosicki', number: 11, position: 'Forward' },
    { name: 'Robert Lewandowski', number: 9, position: 'Forward' },
    { name: 'Arkadiusz Milik', number: 23, position: 'Forward' },
  ],
  // ─── DENMARK ────────────────────────────────────────────────────────────────
  Dinamarca: [
    { name: 'Kasper Schmeichel', number: 1, position: 'Goalkeeper' },
    { name: 'Daniel Wass', number: 5, position: 'Defender' },
    { name: 'Simon Kjær', number: 4, position: 'Defender' },
    { name: 'Andreas Christensen', number: 6, position: 'Defender' },
    { name: 'Joakim Mæhle', number: 2, position: 'Defender' },
    { name: 'Thomas Delaney', number: 8, position: 'Midfielder' },
    { name: 'Pierre-Emile Højbjerg', number: 23, position: 'Midfielder' },
    { name: 'Christian Eriksen', number: 10, position: 'Midfielder' },
    { name: 'Mikkel Damsgaard', number: 16, position: 'Forward' },
    { name: 'Kasper Dolberg', number: 20, position: 'Forward' },
    { name: 'Yussuf Poulsen', number: 20, position: 'Forward' },
  ],
  Denmark: [
    { name: 'Kasper Schmeichel', number: 1, position: 'Goalkeeper' },
    { name: 'Daniel Wass', number: 5, position: 'Defender' },
    { name: 'Simon Kjær', number: 4, position: 'Defender' },
    { name: 'Andreas Christensen', number: 6, position: 'Defender' },
    { name: 'Joakim Mæhle', number: 2, position: 'Defender' },
    { name: 'Thomas Delaney', number: 8, position: 'Midfielder' },
    { name: 'Pierre-Emile Højbjerg', number: 23, position: 'Midfielder' },
    { name: 'Christian Eriksen', number: 10, position: 'Midfielder' },
    { name: 'Mikkel Damsgaard', number: 16, position: 'Forward' },
    { name: 'Kasper Dolberg', number: 20, position: 'Forward' },
    { name: 'Yussuf Poulsen', number: 20, position: 'Forward' },
  ],
  // ─── TURKEY ─────────────────────────────────────────────────────────────────
  Turquía: [
    { name: 'Uğurcan Çakır', number: 1, position: 'Goalkeeper' },
    { name: 'Zeki Çelik', number: 2, position: 'Defender' },
    { name: 'Çağlar Söyüncü', number: 4, position: 'Defender' },
    { name: 'Merih Demiral', number: 3, position: 'Defender' },
    { name: 'Ridvan Yilmaz', number: 13, position: 'Defender' },
    { name: 'Hakan Çalhanoğlu', number: 10, position: 'Midfielder' },
    { name: 'Orkun Kökcü', number: 20, position: 'Midfielder' },
    { name: 'Samet Akaydın', number: 5, position: 'Midfielder' },
    { name: 'Kerem Aktürkoğlu', number: 11, position: 'Forward' },
    { name: 'Baris Alper Yılmaz', number: 7, position: 'Forward' },
    { name: 'Cenk Tosun', number: 9, position: 'Forward' },
  ],
  Turkey: [
    { name: 'Uğurcan Çakır', number: 1, position: 'Goalkeeper' },
    { name: 'Zeki Çelik', number: 2, position: 'Defender' },
    { name: 'Çağlar Söyüncü', number: 4, position: 'Defender' },
    { name: 'Merih Demiral', number: 3, position: 'Defender' },
    { name: 'Ridvan Yilmaz', number: 13, position: 'Defender' },
    { name: 'Hakan Çalhanoğlu', number: 10, position: 'Midfielder' },
    { name: 'Orkun Kökcü', number: 20, position: 'Midfielder' },
    { name: 'Samet Akaydın', number: 5, position: 'Midfielder' },
    { name: 'Kerem Aktürkoğlu', number: 11, position: 'Forward' },
    { name: 'Baris Alper Yılmaz', number: 7, position: 'Forward' },
    { name: 'Cenk Tosun', number: 9, position: 'Forward' },
  ],
  // ─── ECUADOR ────────────────────────────────────────────────────────────────
  Ecuador: [
    { name: 'Hernán Galíndez', number: 1, position: 'Goalkeeper' },
    { name: 'Angelo Preciado', number: 22, position: 'Defender' },
    { name: 'Félix Torres', number: 4, position: 'Defender' },
    { name: 'Piero Hincapié', number: 3, position: 'Defender' },
    { name: 'Pervis Estupiñán', number: 7, position: 'Defender' },
    { name: 'Carlos Gruezo', number: 6, position: 'Midfielder' },
    { name: 'Moisés Caicedo', number: 10, position: 'Midfielder' },
    { name: 'Romario Ibarra', number: 11, position: 'Midfielder' },
    { name: 'Gonzalo Plata', number: 17, position: 'Forward' },
    { name: 'Enner Valencia', number: 13, position: 'Forward' },
    { name: 'Michael Estrada', number: 9, position: 'Forward' },
  ],

  // ─── REP. CHECA (CZECH REPUBLIC) ────────────────────────────────────────────
  'Rep. Checa': [
    { name: 'Jiří Pavlenka', number: 1, position: 'Goalkeeper' },
    { name: 'Vladimír Coufal', number: 5, position: 'Defender' },
    { name: 'Ladislav Krejčí', number: 3, position: 'Defender' },
    { name: 'Tomáš Holeš', number: 6, position: 'Defender' },
    { name: 'David Jurásek', number: 15, position: 'Defender' },
    { name: 'Tomáš Souček', number: 8, position: 'Midfielder' },
    { name: 'Ondřej Souček', number: 11, position: 'Midfielder' },
    { name: 'Lukáš Provod', number: 20, position: 'Midfielder' },
    { name: 'Patrik Schick', number: 9, position: 'Forward' },
    { name: 'Adam Hložek', number: 17, position: 'Forward' },
    { name: 'Mojmír Chytil', number: 13, position: 'Forward' },
  ],
  'Czech Republic': [
    { name: 'Jiří Pavlenka', number: 1, position: 'Goalkeeper' },
    { name: 'Vladimír Coufal', number: 5, position: 'Defender' },
    { name: 'Ladislav Krejčí', number: 3, position: 'Defender' },
    { name: 'Tomáš Holeš', number: 6, position: 'Defender' },
    { name: 'David Jurásek', number: 15, position: 'Defender' },
    { name: 'Tomáš Souček', number: 8, position: 'Midfielder' },
    { name: 'Ondřej Souček', number: 11, position: 'Midfielder' },
    { name: 'Lukáš Provod', number: 20, position: 'Midfielder' },
    { name: 'Patrik Schick', number: 9, position: 'Forward' },
    { name: 'Adam Hložek', number: 17, position: 'Forward' },
    { name: 'Mojmír Chytil', number: 13, position: 'Forward' },
  ],

  // ─── COREA DEL SUR (SOUTH KOREA) ─────────────────────────────────────────────
  'Corea del Sur': [
    { name: 'Kim Seung-gyu', number: 1, position: 'Goalkeeper' },
    { name: 'Kim Moon-hwan', number: 2, position: 'Defender' },
    { name: 'Kim Min-jae', number: 3, position: 'Defender' },
    { name: 'Jung Seung-hyun', number: 6, position: 'Defender' },
    { name: 'Kim Jin-su', number: 13, position: 'Defender' },
    { name: 'Jung Woo-young', number: 16, position: 'Midfielder' },
    { name: 'Lee Jae-sung', number: 10, position: 'Midfielder' },
    { name: 'Hwang In-beom', number: 8, position: 'Midfielder' },
    { name: 'Son Heung-min', number: 7, position: 'Forward' },
    { name: 'Hwang Hee-chan', number: 11, position: 'Forward' },
    { name: 'Cho Gue-sung', number: 9, position: 'Forward' },
  ],
  'South Korea': [
    { name: 'Kim Seung-gyu', number: 1, position: 'Goalkeeper' },
    { name: 'Kim Moon-hwan', number: 2, position: 'Defender' },
    { name: 'Kim Min-jae', number: 3, position: 'Defender' },
    { name: 'Jung Seung-hyun', number: 6, position: 'Defender' },
    { name: 'Kim Jin-su', number: 13, position: 'Defender' },
    { name: 'Jung Woo-young', number: 16, position: 'Midfielder' },
    { name: 'Lee Jae-sung', number: 10, position: 'Midfielder' },
    { name: 'Hwang In-beom', number: 8, position: 'Midfielder' },
    { name: 'Son Heung-min', number: 7, position: 'Forward' },
    { name: 'Hwang Hee-chan', number: 11, position: 'Forward' },
    { name: 'Cho Gue-sung', number: 9, position: 'Forward' },
  ],

  // ─── NORUEGA (NORWAY) ────────────────────────────────────────────────────────
  Noruega: [
    { name: 'Ørjan Nyland', number: 1, position: 'Goalkeeper' },
    { name: 'Kristoffer Ajer', number: 5, position: 'Defender' },
    { name: 'Leo Østigård', number: 4, position: 'Defender' },
    { name: 'Andreas Hanche-Olsen', number: 3, position: 'Defender' },
    { name: 'Marcus Pedersen', number: 2, position: 'Defender' },
    { name: 'Sander Berge', number: 8, position: 'Midfielder' },
    { name: 'Martin Ødegaard', number: 10, position: 'Midfielder' },
    { name: 'Fredrik Aursnes', number: 16, position: 'Midfielder' },
    { name: 'Antonio Nusa', number: 11, position: 'Forward' },
    { name: 'Erling Haaland', number: 9, position: 'Forward' },
    { name: 'Alexander Sørloth', number: 19, position: 'Forward' },
  ],
  Norway: [
    { name: 'Ørjan Nyland', number: 1, position: 'Goalkeeper' },
    { name: 'Kristoffer Ajer', number: 5, position: 'Defender' },
    { name: 'Leo Østigård', number: 4, position: 'Defender' },
    { name: 'Andreas Hanche-Olsen', number: 3, position: 'Defender' },
    { name: 'Marcus Pedersen', number: 2, position: 'Defender' },
    { name: 'Sander Berge', number: 8, position: 'Midfielder' },
    { name: 'Martin Ødegaard', number: 10, position: 'Midfielder' },
    { name: 'Fredrik Aursnes', number: 16, position: 'Midfielder' },
    { name: 'Antonio Nusa', number: 11, position: 'Forward' },
    { name: 'Erling Haaland', number: 9, position: 'Forward' },
    { name: 'Alexander Sørloth', number: 19, position: 'Forward' },
  ],

  // ─── AUSTRIA ─────────────────────────────────────────────────────────────────
  Austria: [
    { name: 'Patrick Pentz', number: 1, position: 'Goalkeeper' },
    { name: 'Stefan Posch', number: 5, position: 'Defender' },
    { name: 'Kevin Danso', number: 4, position: 'Defender' },
    { name: 'Philipp Lienhart', number: 15, position: 'Defender' },
    { name: 'Philipp Mwene', number: 3, position: 'Defender' },
    { name: 'Nicolas Seiwald', number: 8, position: 'Midfielder' },
    { name: 'Marcel Sabitzer', number: 10, position: 'Midfielder' },
    { name: 'Florian Grillitsch', number: 6, position: 'Midfielder' },
    { name: 'Christoph Baumgartner', number: 14, position: 'Forward' },
    { name: 'Michael Gregoritsch', number: 11, position: 'Forward' },
    { name: 'Marko Arnautović', number: 9, position: 'Forward' },
  ],

  // ─── JORDANIA (JORDAN) ───────────────────────────────────────────────────────
  Jordania: [
    { name: 'Amer Shafi', number: 1, position: 'Goalkeeper' },
    { name: 'Baher Jadallah', number: 2, position: 'Defender' },
    { name: 'Yazan Al-Naimat', number: 4, position: 'Defender' },
    { name: 'Ahmad Al-Sarairah', number: 6, position: 'Defender' },
    { name: 'Baha Faisal', number: 3, position: 'Defender' },
    { name: 'Yazan Al-Arab', number: 8, position: 'Midfielder' },
    { name: 'Musa Al-Tamari', number: 10, position: 'Midfielder' },
    { name: 'Abdullah Nasib', number: 16, position: 'Midfielder' },
    { name: 'Ahmad Al-Abbadi', number: 7, position: 'Forward' },
    { name: 'Ahmad Yazan', number: 9, position: 'Forward' },
    { name: 'Zaid Al-Arab', number: 11, position: 'Forward' },
  ],
  Jordan: [
    { name: 'Amer Shafi', number: 1, position: 'Goalkeeper' },
    { name: 'Baher Jadallah', number: 2, position: 'Defender' },
    { name: 'Yazan Al-Naimat', number: 4, position: 'Defender' },
    { name: 'Ahmad Al-Sarairah', number: 6, position: 'Defender' },
    { name: 'Baha Faisal', number: 3, position: 'Defender' },
    { name: 'Yazan Al-Arab', number: 8, position: 'Midfielder' },
    { name: 'Musa Al-Tamari', number: 10, position: 'Midfielder' },
    { name: 'Abdullah Nasib', number: 16, position: 'Midfielder' },
    { name: 'Ahmad Al-Abbadi', number: 7, position: 'Forward' },
    { name: 'Ahmad Yazan', number: 9, position: 'Forward' },
    { name: 'Zaid Al-Arab', number: 11, position: 'Forward' },
  ],

  // ─── R.D. CONGO (DR CONGO) ───────────────────────────────────────────────────
  'R.D. Congo': [
    { name: 'Joël Kiassumbua', number: 1, position: 'Goalkeeper' },
    { name: 'Chancel Mbemba', number: 5, position: 'Defender' },
    { name: 'Marcel Tisserand', number: 3, position: 'Defender' },
    { name: 'Joris Kayembe', number: 2, position: 'Defender' },
    { name: 'Arthur Masuaku', number: 12, position: 'Defender' },
    { name: 'Yannick Bolasie', number: 11, position: 'Midfielder' },
    { name: 'Paul-José Mpoku', number: 10, position: 'Midfielder' },
    { name: 'Willy Boly', number: 6, position: 'Midfielder' },
    { name: 'Cédric Bakambu', number: 9, position: 'Forward' },
    { name: 'Britt Assombalonga', number: 7, position: 'Forward' },
    { name: 'Jonathan Bolingi', number: 19, position: 'Forward' },
  ],
  'DR Congo': [
    { name: 'Joël Kiassumbua', number: 1, position: 'Goalkeeper' },
    { name: 'Chancel Mbemba', number: 5, position: 'Defender' },
    { name: 'Marcel Tisserand', number: 3, position: 'Defender' },
    { name: 'Joris Kayembe', number: 2, position: 'Defender' },
    { name: 'Arthur Masuaku', number: 12, position: 'Defender' },
    { name: 'Yannick Bolasie', number: 11, position: 'Midfielder' },
    { name: 'Paul-José Mpoku', number: 10, position: 'Midfielder' },
    { name: 'Willy Boly', number: 6, position: 'Midfielder' },
    { name: 'Cédric Bakambu', number: 9, position: 'Forward' },
    { name: 'Britt Assombalonga', number: 7, position: 'Forward' },
    { name: 'Jonathan Bolingi', number: 19, position: 'Forward' },
  ],

  // ─── BOSNIA ──────────────────────────────────────────────────────────────────
  Bosnia: [
    { name: 'Ibrahim Šehić', number: 1, position: 'Goalkeeper' },
    { name: 'Sead Kolašinac', number: 5, position: 'Defender' },
    { name: 'Ermin Bičakčić', number: 4, position: 'Defender' },
    { name: 'Ognjen Vranješ', number: 6, position: 'Defender' },
    { name: 'Haris Tabak', number: 3, position: 'Defender' },
    { name: 'Miralem Pjanić', number: 8, position: 'Midfielder' },
    { name: 'Amer Gojak', number: 10, position: 'Midfielder' },
    { name: 'Benjamin Šestić', number: 16, position: 'Midfielder' },
    { name: 'Edin Džeko', number: 9, position: 'Forward' },
    { name: 'Ermedin Demirović', number: 11, position: 'Forward' },
    { name: 'Deni Milošević', number: 7, position: 'Forward' },
  ],

  // ─── CATAR (QATAR) ───────────────────────────────────────────────────────────
  Catar: [
    { name: 'Meshaal Barsham', number: 1, position: 'Goalkeeper' },
    { name: 'Pedro Miguel', number: 2, position: 'Defender' },
    { name: 'Bassam Al-Rawi', number: 5, position: 'Defender' },
    { name: 'Abdelkarim Hassan', number: 3, position: 'Defender' },
    { name: 'Tarek Salman', number: 14, position: 'Defender' },
    { name: 'Karim Boudiaf', number: 8, position: 'Midfielder' },
    { name: 'Akram Afif', number: 11, position: 'Midfielder' },
    { name: 'Abdulaziz Hatem', number: 10, position: 'Midfielder' },
    { name: 'Almoez Ali', number: 19, position: 'Forward' },
    { name: 'Hassan Al-Haydos', number: 10, position: 'Forward' },
    { name: 'Ismaeel Mohammad', number: 9, position: 'Forward' },
  ],
  Qatar: [
    { name: 'Meshaal Barsham', number: 1, position: 'Goalkeeper' },
    { name: 'Pedro Miguel', number: 2, position: 'Defender' },
    { name: 'Bassam Al-Rawi', number: 5, position: 'Defender' },
    { name: 'Abdelkarim Hassan', number: 3, position: 'Defender' },
    { name: 'Tarek Salman', number: 14, position: 'Defender' },
    { name: 'Karim Boudiaf', number: 8, position: 'Midfielder' },
    { name: 'Akram Afif', number: 11, position: 'Midfielder' },
    { name: 'Abdulaziz Hatem', number: 10, position: 'Midfielder' },
    { name: 'Almoez Ali', number: 19, position: 'Forward' },
    { name: 'Hassan Al-Haydos', number: 10, position: 'Forward' },
    { name: 'Ismaeel Mohammad', number: 9, position: 'Forward' },
  ],

  // ─── ESCOCIA (SCOTLAND) ──────────────────────────────────────────────────────
  Escocia: [
    { name: 'Angus Gunn', number: 1, position: 'Goalkeeper' },
    { name: 'Jack Hendry', number: 5, position: 'Defender' },
    { name: 'Scott McKenna', number: 6, position: 'Defender' },
    { name: 'Liam Cooper', number: 4, position: 'Defender' },
    { name: 'Andy Robertson', number: 3, position: 'Defender' },
    { name: 'Callum McGregor', number: 8, position: 'Midfielder' },
    { name: 'John McGinn', number: 7, position: 'Midfielder' },
    { name: 'Billy Gilmour', number: 13, position: 'Midfielder' },
    { name: 'Ryan Christie', number: 10, position: 'Forward' },
    { name: 'Lyndon Dykes', number: 9, position: 'Forward' },
    { name: 'Che Adams', number: 11, position: 'Forward' },
  ],
  Scotland: [
    { name: 'Angus Gunn', number: 1, position: 'Goalkeeper' },
    { name: 'Jack Hendry', number: 5, position: 'Defender' },
    { name: 'Scott McKenna', number: 6, position: 'Defender' },
    { name: 'Liam Cooper', number: 4, position: 'Defender' },
    { name: 'Andy Robertson', number: 3, position: 'Defender' },
    { name: 'Callum McGregor', number: 8, position: 'Midfielder' },
    { name: 'John McGinn', number: 7, position: 'Midfielder' },
    { name: 'Billy Gilmour', number: 13, position: 'Midfielder' },
    { name: 'Ryan Christie', number: 10, position: 'Forward' },
    { name: 'Lyndon Dykes', number: 9, position: 'Forward' },
    { name: 'Che Adams', number: 11, position: 'Forward' },
  ],

  // ─── HAITÍ (HAITI) ───────────────────────────────────────────────────────────
  Haití: [
    { name: 'Josué Duverger', number: 1, position: 'Goalkeeper' },
    { name: 'Andrew Emmanuel', number: 2, position: 'Defender' },
    { name: 'Mechack Jérôme', number: 5, position: 'Defender' },
    { name: 'Steeven Saba', number: 4, position: 'Defender' },
    { name: 'Florent Sebwe', number: 3, position: 'Defender' },
    { name: 'Jeff Louis', number: 8, position: 'Midfielder' },
    { name: 'Wilde-Donald Guerrier', number: 10, position: 'Midfielder' },
    { name: 'Mikerlin Bélizaire', number: 6, position: 'Midfielder' },
    { name: 'Duckens Nazon', number: 11, position: 'Forward' },
    { name: 'Frantzdy Pierrot', number: 9, position: 'Forward' },
    { name: 'Ronaldo Damus', number: 7, position: 'Forward' },
  ],
  Haiti: [
    { name: 'Josué Duverger', number: 1, position: 'Goalkeeper' },
    { name: 'Andrew Emmanuel', number: 2, position: 'Defender' },
    { name: 'Mechack Jérôme', number: 5, position: 'Defender' },
    { name: 'Steeven Saba', number: 4, position: 'Defender' },
    { name: 'Florent Sebwe', number: 3, position: 'Defender' },
    { name: 'Jeff Louis', number: 8, position: 'Midfielder' },
    { name: 'Wilde-Donald Guerrier', number: 10, position: 'Midfielder' },
    { name: 'Mikerlin Bélizaire', number: 6, position: 'Midfielder' },
    { name: 'Duckens Nazon', number: 11, position: 'Forward' },
    { name: 'Frantzdy Pierrot', number: 9, position: 'Forward' },
    { name: 'Ronaldo Damus', number: 7, position: 'Forward' },
  ],

  // ─── AUSTRALIA ───────────────────────────────────────────────────────────────
  Australia: [
    { name: 'Mat Ryan', number: 1, position: 'Goalkeeper' },
    { name: 'Miloš Degenek', number: 2, position: 'Defender' },
    { name: 'Harry Souttar', number: 6, position: 'Defender' },
    { name: 'Kye Rowles', number: 4, position: 'Defender' },
    { name: 'Aziz Behich', number: 3, position: 'Defender' },
    { name: 'Aaron Mooy', number: 8, position: 'Midfielder' },
    { name: 'Jackson Irvine', number: 16, position: 'Midfielder' },
    { name: 'Riley McGree', number: 10, position: 'Midfielder' },
    { name: 'Awer Mabil', number: 11, position: 'Forward' },
    { name: 'Mitch Duke', number: 9, position: 'Forward' },
    { name: 'Marco Tilio', number: 7, position: 'Forward' },
  ],

  // ─── COSTA DE MARFIL (IVORY COAST) ───────────────────────────────────────────
  'Costa de Marfil': [
    { name: 'Yahia Fofana', number: 1, position: 'Goalkeeper' },
    { name: 'Serge Aurier', number: 2, position: 'Defender' },
    { name: 'Willy Boly', number: 3, position: 'Defender' },
    { name: 'Simon Deli', number: 5, position: 'Defender' },
    { name: 'Ghislain Konan', number: 12, position: 'Defender' },
    { name: 'Franck Kessié', number: 8, position: 'Midfielder' },
    { name: 'Ibrahim Sangaré', number: 6, position: 'Midfielder' },
    { name: 'Jean-Michaël Seri', number: 11, position: 'Midfielder' },
    { name: 'Nicolas Pépé', number: 17, position: 'Forward' },
    { name: 'Wilfried Zaha', number: 7, position: 'Forward' },
    { name: 'Sébastien Haller', number: 9, position: 'Forward' },
  ],
  'Ivory Coast': [
    { name: 'Yahia Fofana', number: 1, position: 'Goalkeeper' },
    { name: 'Serge Aurier', number: 2, position: 'Defender' },
    { name: 'Willy Boly', number: 3, position: 'Defender' },
    { name: 'Simon Deli', number: 5, position: 'Defender' },
    { name: 'Ghislain Konan', number: 12, position: 'Defender' },
    { name: 'Franck Kessié', number: 8, position: 'Midfielder' },
    { name: 'Ibrahim Sangaré', number: 6, position: 'Midfielder' },
    { name: 'Jean-Michaël Seri', number: 11, position: 'Midfielder' },
    { name: 'Nicolas Pépé', number: 17, position: 'Forward' },
    { name: 'Wilfried Zaha', number: 7, position: 'Forward' },
    { name: 'Sébastien Haller', number: 9, position: 'Forward' },
  ],

  // ─── CURAZAO (CURACAO) ───────────────────────────────────────────────────────
  Curazao: [
    { name: 'Eloy Room', number: 1, position: 'Goalkeeper' },
    { name: 'Cuco Martina', number: 2, position: 'Defender' },
    { name: 'Rangelo Janga', number: 5, position: 'Defender' },
    { name: 'Leandro Bacuna', number: 6, position: 'Defender' },
    { name: 'Ruishendley Colastica', number: 3, position: 'Defender' },
    { name: 'Stendly Schoop', number: 8, position: 'Midfielder' },
    { name: 'Giliano Wijnaldum', number: 10, position: 'Midfielder' },
    { name: 'Henrico Drost', number: 16, position: 'Midfielder' },
    { name: 'Juriën Timber', number: 4, position: 'Forward' },
    { name: 'Dwayne Rigters', number: 9, position: 'Forward' },
    { name: 'Chedric Baas', number: 11, position: 'Forward' },
  ],
  Curacao: [
    { name: 'Eloy Room', number: 1, position: 'Goalkeeper' },
    { name: 'Cuco Martina', number: 2, position: 'Defender' },
    { name: 'Rangelo Janga', number: 5, position: 'Defender' },
    { name: 'Leandro Bacuna', number: 6, position: 'Defender' },
    { name: 'Ruishendley Colastica', number: 3, position: 'Defender' },
    { name: 'Stendly Schoop', number: 8, position: 'Midfielder' },
    { name: 'Giliano Wijnaldum', number: 10, position: 'Midfielder' },
    { name: 'Henrico Drost', number: 16, position: 'Midfielder' },
    { name: 'Juriën Timber', number: 4, position: 'Forward' },
    { name: 'Dwayne Rigters', number: 9, position: 'Forward' },
    { name: 'Chedric Baas', number: 11, position: 'Forward' },
  ],

  // ─── SUECIA (SWEDEN) ─────────────────────────────────────────────────────────
  Suecia: [
    { name: 'Robin Olsen', number: 1, position: 'Goalkeeper' },
    { name: 'Emil Krafth', number: 2, position: 'Defender' },
    { name: 'Carl Starfelt', number: 5, position: 'Defender' },
    { name: 'Filip Helander', number: 6, position: 'Defender' },
    { name: 'Ludwig Augustinsson', number: 3, position: 'Defender' },
    { name: 'Albin Ekdal', number: 8, position: 'Midfielder' },
    { name: 'Viktor Claesson', number: 10, position: 'Midfielder' },
    { name: 'Dejan Kulusevski', number: 21, position: 'Midfielder' },
    { name: 'Jesper Karlsson', number: 17, position: 'Forward' },
    { name: 'Alexander Isak', number: 9, position: 'Forward' },
    { name: 'Jordan Larsson', number: 11, position: 'Forward' },
  ],
  Sweden: [
    { name: 'Robin Olsen', number: 1, position: 'Goalkeeper' },
    { name: 'Emil Krafth', number: 2, position: 'Defender' },
    { name: 'Carl Starfelt', number: 5, position: 'Defender' },
    { name: 'Filip Helander', number: 6, position: 'Defender' },
    { name: 'Ludwig Augustinsson', number: 3, position: 'Defender' },
    { name: 'Albin Ekdal', number: 8, position: 'Midfielder' },
    { name: 'Viktor Claesson', number: 10, position: 'Midfielder' },
    { name: 'Dejan Kulusevski', number: 21, position: 'Midfielder' },
    { name: 'Jesper Karlsson', number: 17, position: 'Forward' },
    { name: 'Alexander Isak', number: 9, position: 'Forward' },
    { name: 'Jordan Larsson', number: 11, position: 'Forward' },
  ],

  // ─── TÚNEZ (TUNISIA) ─────────────────────────────────────────────────────────
  Túnez: [
    { name: 'Aymen Dahmen', number: 1, position: 'Goalkeeper' },
    { name: 'Wajdi Kechrida', number: 2, position: 'Defender' },
    { name: 'Montassar Talbi', number: 5, position: 'Defender' },
    { name: 'Dylan Bronn', number: 4, position: 'Defender' },
    { name: 'Mohamed Drager', number: 3, position: 'Defender' },
    { name: 'Ellyes Skhiri', number: 8, position: 'Midfielder' },
    { name: 'Aissa Laidouni', number: 6, position: 'Midfielder' },
    { name: 'Hannibal Mejbri', number: 10, position: 'Midfielder' },
    { name: 'Youssef Msakni', number: 7, position: 'Forward' },
    { name: 'Issam Jebali', number: 9, position: 'Forward' },
    { name: 'Seifeddine Jaziri', number: 11, position: 'Forward' },
  ],
  Tunisia: [
    { name: 'Aymen Dahmen', number: 1, position: 'Goalkeeper' },
    { name: 'Wajdi Kechrida', number: 2, position: 'Defender' },
    { name: 'Montassar Talbi', number: 5, position: 'Defender' },
    { name: 'Dylan Bronn', number: 4, position: 'Defender' },
    { name: 'Mohamed Drager', number: 3, position: 'Defender' },
    { name: 'Ellyes Skhiri', number: 8, position: 'Midfielder' },
    { name: 'Aissa Laidouni', number: 6, position: 'Midfielder' },
    { name: 'Hannibal Mejbri', number: 10, position: 'Midfielder' },
    { name: 'Youssef Msakni', number: 7, position: 'Forward' },
    { name: 'Issam Jebali', number: 9, position: 'Forward' },
    { name: 'Seifeddine Jaziri', number: 11, position: 'Forward' },
  ],

  // ─── IRÁN (IRAN) ─────────────────────────────────────────────────────────────
  Irán: [
    { name: 'Alireza Beiranvand', number: 1, position: 'Goalkeeper' },
    { name: 'Sadegh Moharrami', number: 2, position: 'Defender' },
    { name: 'Majid Hosseini', number: 5, position: 'Defender' },
    { name: 'Shoja Khalilzadeh', number: 3, position: 'Defender' },
    { name: 'Ehsan Hajsafi', number: 6, position: 'Defender' },
    { name: 'Ahmad Nourollahi', number: 8, position: 'Midfielder' },
    { name: 'Saeid Ezatolahi', number: 16, position: 'Midfielder' },
    { name: 'Alireza Jahanbakhsh', number: 7, position: 'Midfielder' },
    { name: 'Sardar Azmoun', number: 9, position: 'Forward' },
    { name: 'Mehdi Taremi', number: 9, position: 'Forward' },
    { name: 'Ali Gholizadeh', number: 11, position: 'Forward' },
  ],
  Iran: [
    { name: 'Alireza Beiranvand', number: 1, position: 'Goalkeeper' },
    { name: 'Sadegh Moharrami', number: 2, position: 'Defender' },
    { name: 'Majid Hosseini', number: 5, position: 'Defender' },
    { name: 'Shoja Khalilzadeh', number: 3, position: 'Defender' },
    { name: 'Ehsan Hajsafi', number: 6, position: 'Defender' },
    { name: 'Ahmad Nourollahi', number: 8, position: 'Midfielder' },
    { name: 'Saeid Ezatolahi', number: 16, position: 'Midfielder' },
    { name: 'Alireza Jahanbakhsh', number: 7, position: 'Midfielder' },
    { name: 'Sardar Azmoun', number: 9, position: 'Forward' },
    { name: 'Mehdi Taremi', number: 9, position: 'Forward' },
    { name: 'Ali Gholizadeh', number: 11, position: 'Forward' },
  ],

  // ─── EGIPTO (EGYPT) ──────────────────────────────────────────────────────────
  Egipto: [
    { name: 'Mohamed Abou Gabal', number: 1, position: 'Goalkeeper' },
    { name: 'Ahmed Hegazi', number: 5, position: 'Defender' },
    { name: 'Mohamed Abdelmonem', number: 4, position: 'Defender' },
    { name: 'Ayman Ashraf', number: 3, position: 'Defender' },
    { name: 'Omar Kamal', number: 2, position: 'Defender' },
    { name: 'Mohamed Elneny', number: 8, position: 'Midfielder' },
    { name: 'Amr El Sulaya', number: 10, position: 'Midfielder' },
    { name: 'Tarek Hamed', number: 6, position: 'Midfielder' },
    { name: 'Mohamed Salah', number: 11, position: 'Forward' },
    { name: 'Omar Marmoush', number: 9, position: 'Forward' },
    { name: 'Mostafa Mohamed', number: 7, position: 'Forward' },
  ],
  Egypt: [
    { name: 'Mohamed Abou Gabal', number: 1, position: 'Goalkeeper' },
    { name: 'Ahmed Hegazi', number: 5, position: 'Defender' },
    { name: 'Mohamed Abdelmonem', number: 4, position: 'Defender' },
    { name: 'Ayman Ashraf', number: 3, position: 'Defender' },
    { name: 'Omar Kamal', number: 2, position: 'Defender' },
    { name: 'Mohamed Elneny', number: 8, position: 'Midfielder' },
    { name: 'Amr El Sulaya', number: 10, position: 'Midfielder' },
    { name: 'Tarek Hamed', number: 6, position: 'Midfielder' },
    { name: 'Mohamed Salah', number: 11, position: 'Forward' },
    { name: 'Omar Marmoush', number: 9, position: 'Forward' },
    { name: 'Mostafa Mohamed', number: 7, position: 'Forward' },
  ],

  // ─── NUEVA ZELANDA (NEW ZEALAND) ──────────────────────────────────────────────
  'Nueva Zelanda': [
    { name: 'Michael Woud', number: 1, position: 'Goalkeeper' },
    { name: 'Niko Kirwan', number: 2, position: 'Defender' },
    { name: 'Winston Reid', number: 5, position: 'Defender' },
    { name: 'Michael Boxall', number: 4, position: 'Defender' },
    { name: 'Liberato Cacace', number: 3, position: 'Defender' },
    { name: 'Clayton Lewis', number: 8, position: 'Midfielder' },
    { name: 'Bill Tuilagi', number: 6, position: 'Midfielder' },
    { name: 'Sarpreet Singh', number: 10, position: 'Midfielder' },
    { name: 'Chris Wood', number: 9, position: 'Forward' },
    { name: 'Kosta Barbarouses', number: 11, position: 'Forward' },
    { name: 'Marco Rojas', number: 7, position: 'Forward' },
  ],
  'New Zealand': [
    { name: 'Michael Woud', number: 1, position: 'Goalkeeper' },
    { name: 'Niko Kirwan', number: 2, position: 'Defender' },
    { name: 'Winston Reid', number: 5, position: 'Defender' },
    { name: 'Michael Boxall', number: 4, position: 'Defender' },
    { name: 'Liberato Cacace', number: 3, position: 'Defender' },
    { name: 'Clayton Lewis', number: 8, position: 'Midfielder' },
    { name: 'Bill Tuilagi', number: 6, position: 'Midfielder' },
    { name: 'Sarpreet Singh', number: 10, position: 'Midfielder' },
    { name: 'Chris Wood', number: 9, position: 'Forward' },
    { name: 'Kosta Barbarouses', number: 11, position: 'Forward' },
    { name: 'Marco Rojas', number: 7, position: 'Forward' },
  ],

  // ─── ARABIA SAUDITA (SAUDI ARABIA) ───────────────────────────────────────────
  'Arabia Saudita': [
    { name: 'Mohammed Al-Owais', number: 1, position: 'Goalkeeper' },
    { name: 'Sultan Al-Ghannam', number: 2, position: 'Defender' },
    { name: 'Ali Al-Bulayhi', number: 13, position: 'Defender' },
    { name: 'Hassan Al-Tambakti', number: 4, position: 'Defender' },
    { name: 'Yasser Al-Shahrani', number: 3, position: 'Defender' },
    { name: 'Mohammed Kanno', number: 8, position: 'Midfielder' },
    { name: 'Sami Al-Najei', number: 6, position: 'Midfielder' },
    { name: 'Abdulrahman Al-Aboud', number: 10, position: 'Midfielder' },
    { name: 'Salem Al-Dawsari', number: 11, position: 'Forward' },
    { name: 'Firas Al-Buraikan', number: 9, position: 'Forward' },
    { name: 'Saleh Al-Shehri', number: 7, position: 'Forward' },
  ],
  'Saudi Arabia': [
    { name: 'Mohammed Al-Owais', number: 1, position: 'Goalkeeper' },
    { name: 'Sultan Al-Ghannam', number: 2, position: 'Defender' },
    { name: 'Ali Al-Bulayhi', number: 13, position: 'Defender' },
    { name: 'Hassan Al-Tambakti', number: 4, position: 'Defender' },
    { name: 'Yasser Al-Shahrani', number: 3, position: 'Defender' },
    { name: 'Mohammed Kanno', number: 8, position: 'Midfielder' },
    { name: 'Sami Al-Najei', number: 6, position: 'Midfielder' },
    { name: 'Abdulrahman Al-Aboud', number: 10, position: 'Midfielder' },
    { name: 'Salem Al-Dawsari', number: 11, position: 'Forward' },
    { name: 'Firas Al-Buraikan', number: 9, position: 'Forward' },
    { name: 'Saleh Al-Shehri', number: 7, position: 'Forward' },
  ],

  // ─── CABO VERDE (CAPE VERDE) ──────────────────────────────────────────────────
  'Cabo Verde': [
    { name: 'Vozinha', number: 1, position: 'Goalkeeper' },
    { name: 'Jeffry Fortes', number: 2, position: 'Defender' },
    { name: 'Stopira', number: 5, position: 'Defender' },
    { name: 'Dylan Tavares', number: 3, position: 'Defender' },
    { name: 'Diney', number: 4, position: 'Defender' },
    { name: 'Jamiro Monteiro', number: 8, position: 'Midfielder' },
    { name: 'Garry Rodrigues', number: 11, position: 'Midfielder' },
    { name: 'Kenny Rocha', number: 6, position: 'Midfielder' },
    { name: 'Ryan Mendes', number: 7, position: 'Forward' },
    { name: 'Hélio Varela', number: 10, position: 'Forward' },
    { name: 'Andrelinho', number: 9, position: 'Forward' },
  ],
  'Cape Verde': [
    { name: 'Vozinha', number: 1, position: 'Goalkeeper' },
    { name: 'Jeffry Fortes', number: 2, position: 'Defender' },
    { name: 'Stopira', number: 5, position: 'Defender' },
    { name: 'Dylan Tavares', number: 3, position: 'Defender' },
    { name: 'Diney', number: 4, position: 'Defender' },
    { name: 'Jamiro Monteiro', number: 8, position: 'Midfielder' },
    { name: 'Garry Rodrigues', number: 11, position: 'Midfielder' },
    { name: 'Kenny Rocha', number: 6, position: 'Midfielder' },
    { name: 'Ryan Mendes', number: 7, position: 'Forward' },
    { name: 'Hélio Varela', number: 10, position: 'Forward' },
    { name: 'Andrelinho', number: 9, position: 'Forward' },
  ],

  // ─── IRAK (IRAQ) ─────────────────────────────────────────────────────────────
  Irak: [
    { name: 'Jalal Hassan', number: 1, position: 'Goalkeeper' },
    { name: 'Ali Adnan', number: 3, position: 'Defender' },
    { name: 'Salam Shakir', number: 5, position: 'Defender' },
    { name: 'Hussein Ali', number: 4, position: 'Defender' },
    { name: 'Rebin Sulaka', number: 2, position: 'Defender' },
    { name: 'Amjad Attwan', number: 8, position: 'Midfielder' },
    { name: 'Safaa Hadi', number: 6, position: 'Midfielder' },
    { name: 'Mohanad Ali', number: 10, position: 'Midfielder' },
    { name: 'Aymen Hussein', number: 9, position: 'Forward' },
    { name: 'Mohannad Abdul-Raheem', number: 11, position: 'Forward' },
    { name: 'Ahmed Yasin', number: 7, position: 'Forward' },
  ],
  Iraq: [
    { name: 'Jalal Hassan', number: 1, position: 'Goalkeeper' },
    { name: 'Ali Adnan', number: 3, position: 'Defender' },
    { name: 'Salam Shakir', number: 5, position: 'Defender' },
    { name: 'Hussein Ali', number: 4, position: 'Defender' },
    { name: 'Rebin Sulaka', number: 2, position: 'Defender' },
    { name: 'Amjad Attwan', number: 8, position: 'Midfielder' },
    { name: 'Safaa Hadi', number: 6, position: 'Midfielder' },
    { name: 'Mohanad Ali', number: 10, position: 'Midfielder' },
    { name: 'Aymen Hussein', number: 9, position: 'Forward' },
    { name: 'Mohannad Abdul-Raheem', number: 11, position: 'Forward' },
    { name: 'Ahmed Yasin', number: 7, position: 'Forward' },
  ],

  // ─── GHANA ───────────────────────────────────────────────────────────────────
  Ghana: [
    { name: 'Lawrence Ati-Zigi', number: 1, position: 'Goalkeeper' },
    { name: 'Tariq Lamptey', number: 2, position: 'Defender' },
    { name: 'Daniel Amartey', number: 5, position: 'Defender' },
    { name: 'Alexander Djiku', number: 4, position: 'Defender' },
    { name: 'Gideon Mensah', number: 3, position: 'Defender' },
    { name: 'Thomas Partey', number: 5, position: 'Midfielder' },
    { name: 'Salis Abdul Samed', number: 8, position: 'Midfielder' },
    { name: 'Mohammed Kudus', number: 10, position: 'Midfielder' },
    { name: 'Iñaki Williams', number: 9, position: 'Forward' },
    { name: 'Antoine Semenyo', number: 11, position: 'Forward' },
    { name: 'Jordan Ayew', number: 7, position: 'Forward' },
  ],

  // ─── PANAMÁ (PANAMA) ─────────────────────────────────────────────────────────
  Panamá: [
    { name: 'Luis Mejía', number: 1, position: 'Goalkeeper' },
    { name: 'Harold Cummings', number: 5, position: 'Defender' },
    { name: 'Fidel Escobar', number: 4, position: 'Defender' },
    { name: 'Eric Davis', number: 3, position: 'Defender' },
    { name: 'Andrés Andrade', number: 2, position: 'Defender' },
    { name: 'Adalberto Carrasquilla', number: 8, position: 'Midfielder' },
    { name: 'Anibal Godoy', number: 6, position: 'Midfielder' },
    { name: 'Armando Cooper', number: 10, position: 'Midfielder' },
    { name: 'Gabriel Torres', number: 9, position: 'Forward' },
    { name: 'Ismael Díaz', number: 11, position: 'Forward' },
    { name: 'Cecilio Waterman', number: 7, position: 'Forward' },
  ],
  Panama: [
    { name: 'Luis Mejía', number: 1, position: 'Goalkeeper' },
    { name: 'Harold Cummings', number: 5, position: 'Defender' },
    { name: 'Fidel Escobar', number: 4, position: 'Defender' },
    { name: 'Eric Davis', number: 3, position: 'Defender' },
    { name: 'Andrés Andrade', number: 2, position: 'Defender' },
    { name: 'Adalberto Carrasquilla', number: 8, position: 'Midfielder' },
    { name: 'Anibal Godoy', number: 6, position: 'Midfielder' },
    { name: 'Armando Cooper', number: 10, position: 'Midfielder' },
    { name: 'Gabriel Torres', number: 9, position: 'Forward' },
    { name: 'Ismael Díaz', number: 11, position: 'Forward' },
    { name: 'Cecilio Waterman', number: 7, position: 'Forward' },
  ],

  // ─── PARAGUAY ────────────────────────────────────────────────────────────────
  Paraguay: [
    { name: 'Antony Silva', number: 1, position: 'Goalkeeper' },
    { name: 'Gustavo Gómez', number: 3, position: 'Defender' },
    { name: 'Omar Alderete', number: 4, position: 'Defender' },
    { name: 'Fabián Balbuena', number: 5, position: 'Defender' },
    { name: 'Santiago Arzamendia', number: 3, position: 'Defender' },
    { name: 'Mathías Villasanti', number: 8, position: 'Midfielder' },
    { name: 'Óscar Romero', number: 10, position: 'Midfielder' },
    { name: 'Celso Ortiz', number: 6, position: 'Midfielder' },
    { name: 'Julio Enciso', number: 11, position: 'Forward' },
    { name: 'Ramón Sosa', number: 7, position: 'Forward' },
    { name: 'Antonio Sanabria', number: 9, position: 'Forward' },
  ],

  // ─── ESTADOS UNIDOS (USA already exists as 'USA') ─── alias
  'Estados Unidos': [
    { name: 'Matt Turner', number: 1, position: 'Goalkeeper' },
    { name: 'Sergino Dest', number: 2, position: 'Defender' },
    { name: 'Chris Richards', number: 5, position: 'Defender' },
    { name: 'Miles Robinson', number: 4, position: 'Defender' },
    { name: 'Antonee Robinson', number: 3, position: 'Defender' },
    { name: 'Tyler Adams', number: 8, position: 'Midfielder' },
    { name: 'Weston McKennie', number: 8, position: 'Midfielder' },
    { name: 'Yunus Musah', number: 6, position: 'Midfielder' },
    { name: 'Christian Pulisic', number: 10, position: 'Forward' },
    { name: 'Gio Reyna', number: 7, position: 'Forward' },
    { name: 'Ricardo Pepi', number: 9, position: 'Forward' },
  ],
};

// ─── Lookup function with fuzzy matching ─────────────────────────────────────
export function getWcSquad(teamName: string): SquadPlayer[] {
  if (!teamName) return [];

  // Direct match first
  if (WC_SQUADS[teamName]) return WC_SQUADS[teamName];

  // Case-insensitive match
  const lower = teamName.toLowerCase();
  const key = Object.keys(WC_SQUADS).find(k => k.toLowerCase() === lower);
  if (key) return WC_SQUADS[key];

  // Partial match (e.g. "R.D. Congo" → "RD Congo", "Rep. Dem. Congo" → "DR Congo")
  const partialKey = Object.keys(WC_SQUADS).find(k => {
    const kLower = k.toLowerCase().replace(/[.\s-]/g, '');
    const nameLower = lower.replace(/[.\s-]/g, '');
    return kLower.includes(nameLower) || nameLower.includes(kLower);
  });
  if (partialKey) return WC_SQUADS[partialKey];

  return [];
}
